const APP_VERSION="0.1.0",STORAGE_KEY="adaptive_phrasal_verbs_v1",SESSION_SIZE=15,TIME_LIMIT=15;
const BANK=window.PHRASAL_BANK||[],BY_ID=Object.fromEntries(BANK.map(x=>[x.id,x])),PERSONAL_PRIORITY=new Set(["split_up"]);
let state=loadState(),session=null,current=null,timerHandle=null,deadline=0,locked=false;
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function blankItem(){return{attempts:0,correct:0,totalTime:0,avgTime:0,streak:0,bestStreak:0,lastSeen:0,misses:0};}
function freshState(){return{version:1,level:1,sessions:0,answers:0,correct:0,items:{},confusions:{},history:[]};}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")||freshState();for(const x of BANK)s.items[x.id]=Object.assign(blankItem(),s.items[x.id]||{});return s;}catch(e){const s=freshState();for(const x of BANK)s.items[x.id]=blankItem();return s;}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function itemStats(x){return state.items[x.id]||(state.items[x.id]=blankItem());}
function mastery(x){const m=itemStats(x);if(!m.attempts)return 0;const acc=m.correct/m.attempts,exp=Math.min(1,m.attempts/8),speed=clamp((TIME_LIMIT-m.avgTime)/TIME_LIMIT,0,1),streak=Math.min(1,m.streak/4);return Math.round((acc*.55+exp*.20+speed*.15+streak*.10)*100);}
function globalMastery(){return BANK.length?Math.round(BANK.reduce((n,x)=>n+mastery(x),0)/BANK.length):0;}
function coverage(){return BANK.length?Math.round(BANK.filter(x=>itemStats(x).attempts>0).length/BANK.length*100):0;}
function allAccuracy(){return state.answers?Math.round(state.correct/state.answers*100):null;}
function focusItems(limit=5){const attempted=BANK.filter(x=>itemStats(x).attempts).sort((a,b)=>mastery(a)-mastery(b)||itemStats(b).misses-itemStats(a).misses);const unseen=BANK.filter(x=>!itemStats(x).attempts);return [...attempted,...unseen].slice(0,limit);}
function applyTheme(){const bands=[["#163427","#123023","#10271d"],["#123b3a","#103131","#0c2829"],["#173b5a","#122f4c","#10263d"],["#34365f","#282b50","#202441"],["#51401d","#403217","#302712"],["#66531a","#4f400f","#382d0b"]];const i=state.level<=3?0:state.level<=6?1:state.level<=9?2:state.level<=11?3:state.level<=13?4:5;const [top,mid,bg]=bands[i];document.documentElement.style.setProperty("--bg-top",top);document.documentElement.style.setProperty("--bg-mid",mid);document.documentElement.style.setProperty("--bg",bg);}
function showScreen(id){for(const x of ["startScreen","gameScreen","endScreen","statsScreen"])$(x).classList.toggle("hidden",x!==id);window.scrollTo(0,0);}
function focusHtml(items){return items.map(x=>{const p=mastery(x),label=itemStats(x).attempts?p+"%":"NEW";return '<div class="focusrow"><b>'+x.pv+'</b><div class="track"><div class="fill" style="width:'+p+'%"></div></div><span>'+label+'</span></div>';}).join("");}
function renderHome(){applyTheme();$("homeLevel").textContent=state.level;$("homeAccuracy").textContent=allAccuracy()===null?"—":allAccuracy()+"%";$("homeCoverage").textContent=coverage()+"%";$("homeMastery").textContent=globalMastery()+"%";$("homeSessions").textContent=state.sessions;$("homeFocus").innerHTML=focusHtml(focusItems());const unseen=BANK.filter(x=>!itemStats(x).attempts).length;$("homeStatus").textContent=unseen?unseen+" of 50 are still unseen. The scheduler gives them priority while recycling your weakest contrasts.":"All 50 have appeared. From now on the scheduler concentrates on weak items, slow answers and confusions.";}
function weightFor(x){const m=itemStats(x),weak=(100-mastery(x))/18,unseen=m.attempts?0:6,miss=Math.min(4,m.misses*.35),personal=PERSONAL_PRIORITY.has(x.id)?1.5:0,levelFit=x.difficulty<=Math.ceil(state.level/4)+1?1.3:.5;return 1+weak+unseen+miss+personal+levelFit;}
function pickWeighted(pool){const weights=pool.map(weightFor),sum=weights.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<pool.length;i++){r-=weights[i];if(r<=0)return pool[i];}return pool[pool.length-1];}
function buildQueue(){const pool=[...BANK],out=[];while(out.length<SESSION_SIZE&&pool.length){const x=pickWeighted(pool);out.push(x);pool.splice(pool.indexOf(x),1);}return out;}
function pickType(x){const a=itemStats(x).attempts,r=Math.random();if(a<2)return r<.68?"context":r<.88?"meaning":"spanish";if(state.level<4)return r<.56?"context":r<.78?"meaning":r<.90?"spanish":"contrast";if(state.level<8)return r<.55?"context":r<.74?"meaning":r<.90?"contrast":"cambridge";return r<.45?"context":r<.60?"meaning":r<.84?"contrast":"cambridge";}
function distractors(target,type){const base=target.pv.split(" ")[0];const ranked=BANK.filter(x=>x.id!==target.id).map(x=>{let score=Math.random()*2;if(x.pv.split(" ")[0]===base)score+=type==="contrast"?14:7;if(x.tag===target.tag)score+=type==="contrast"?7:4;if(x.difficulty===target.difficulty)score+=1;return{x,score};}).sort((a,b)=>b.score-a.score);const pool=ranked.slice(0,Math.min(12,ranked.length));const out=[];while(out.length<3&&pool.length){const span=Math.min(pool.length,6);const i=Math.floor(Math.random()*span);out.push(pool.splice(i,1)[0].x);}return out;}
function makeQuestion(target,index){const type=pickType(target),m=itemStats(target),ctx=target.contexts[(m.attempts+index)%target.contexts.length];let text,kicker;if(type==="meaning"){text='Which phrasal verb means “'+target.en+'”?';kicker="MEANING";}else if(type==="spanish"){text='¿Cuál significa “'+target.es+'”?';kicker="ES → EN";}else if(type==="contrast"){text=ctx;kicker="CLOSE CONTRAST";}else if(type==="cambridge"){text="Complete the sentence: "+ctx;kicker="B2 USE OF ENGLISH";}else{text=ctx;kicker="CONTEXT";}const opts=shuffle([target,...distractors(target,type)]);return{target,type,text,kicker,options:opts};}
function startSession(){session={queue:buildQueue(),index:0,correct:0,times:[],errors:[],started:Date.now()};showScreen("gameScreen");$("gameLevel").textContent=state.level;renderSegments();nextQuestion();}
function renderSegments(){const box=$("segments");box.innerHTML="";for(let i=0;i<SESSION_SIZE;i++){const d=document.createElement("div");d.className="seg"+(session&&i<session.index?" on":"");box.appendChild(d);}}
function nextQuestion(){clearInterval(timerHandle);locked=false;if(!session||session.index>=SESSION_SIZE){finishSession();return;}const target=session.queue[session.index];current=makeQuestion(target,session.index);$("qIndex").textContent=session.index+1;$("qType").textContent=current.kicker;$("questionText").textContent=current.text;const box=$("answers");box.innerHTML="";current.options.forEach(opt=>{const b=document.createElement("button");b.className="answer";b.textContent=opt.pv;b.dataset.id=opt.id;b.addEventListener("click",()=>answer(opt.id));box.appendChild(b);});deadline=Date.now()+TIME_LIMIT*1000;tick();timerHandle=setInterval(tick,100);}
function tick(){const ms=Math.max(0,deadline-Date.now()),sec=Math.ceil(ms/1000),pct=ms/(TIME_LIMIT*1000)*100;$("timerText").textContent=sec;$("timerText").parentElement.style.setProperty("--timer-cut",(100-pct)+"%");if(ms<=0){clearInterval(timerHandle);answer(null,true);}}
function answer(choiceId,timeout=false){if(locked)return;locked=true;clearInterval(timerHandle);const elapsed=clamp((TIME_LIMIT*1000-Math.max(0,deadline-Date.now()))/1000,0,TIME_LIMIT),target=current.target,ok=choiceId===target.id,m=itemStats(target);m.attempts++;m.totalTime+=elapsed;m.avgTime=m.totalTime/m.attempts;m.lastSeen=Date.now();if(ok){m.correct++;m.streak++;m.bestStreak=Math.max(m.bestStreak,m.streak);state.correct++;session.correct++;}else{m.streak=0;m.misses++;if(choiceId){const key=target.id+"|"+choiceId;state.confusions[key]=(state.confusions[key]||0)+1;}session.errors.push({target:target.id,choice:choiceId,timeout,question:current.text});}
state.answers++;session.times.push(elapsed);const buttons=[...$("answers").children];buttons.forEach(b=>{b.disabled=true;if(b.dataset.id===target.id)b.classList.add("good");else if(b.dataset.id===choiceId)b.classList.add("bad");else b.classList.add("dim");});showFeedback(ok,timeout,target);save();setTimeout(()=>{session.index++;renderSegments();nextQuestion();},900);}
function showFeedback(ok,timeout,target){const f=$("feedback");f.className="feedback "+(ok?"":"no");$("feedbackLabel").textContent=ok?"Correct":timeout?"Time":"Not quite";$("feedbackDetail").innerHTML=target.pv+"<small>"+target.en+"</small>";requestAnimationFrame(()=>f.classList.add("show"));setTimeout(()=>f.classList.remove("show"),700);}
function finishSession(){clearInterval(timerHandle);const acc=session.correct/SESSION_SIZE,old=state.level;if(acc>=.80)state.level=Math.min(15,state.level+1);else if(acc<.47)state.level=Math.max(1,state.level-1);state.sessions++;state.history.push({at:Date.now(),score:session.correct,total:SESSION_SIZE,levelBefore:old,levelAfter:state.level,avgTime:session.times.reduce((a,b)=>a+b,0)/session.times.length});state.history=state.history.slice(-300);save();renderEnd(old);showScreen("endScreen");}
function renderEnd(oldLevel){const acc=Math.round(session.correct/SESSION_SIZE*100),avg=session.times.length?session.times.reduce((a,b)=>a+b,0)/session.times.length:0;$("endScore").textContent=session.correct+"/"+SESSION_SIZE;$("endAccuracy").textContent=acc+"%";$("endAvgTime").textContent=avg.toFixed(1)+" s";$("endLevel").textContent=state.level;$("endMastery").textContent=globalMastery()+"%";$("endMessage").textContent=state.level>oldLevel?"Level up · harder contrasts unlocked.":state.level<oldLevel?"Level adjusted · more reinforcement next.":"Level held · scheduler will rebalance."; $("endFocus").innerHTML=focusHtml(focusItems());renderErrors();}
function renderErrors(){const box=$("errorList");if(!session.errors.length){box.innerHTML='<div class="statusbox">Perfect session: no errors to review.</div>';return;}box.innerHTML="<h3>Review errors</h3>"+session.errors.map(e=>{const t=BY_ID[e.target],c=e.choice?BY_ID[e.choice]:null;return '<details><summary>'+t.pv+' · '+(e.timeout?"TIME":c?("you chose "+c.pv):"wrong")+'</summary><p>'+e.question+'<br><strong>'+t.pv+'</strong> = '+t.en+'</p></details>';}).join("");}
function confusionRows(limit=8){return Object.entries(state.confusions).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([key,n])=>{const [a,b]=key.split("|"),A=BY_ID[a],B=BY_ID[b];if(!A||!B)return"";return '<div class="focusrow"><b>'+A.pv+' ↔ '+B.pv+'</b><div class="track"><div class="fill" style="width:'+Math.min(100,n*16)+'%"></div></div><span>'+n+'×</span></div>';}).join("")||'<div class="statusbox">No confusion pairs yet.</div>';}
function renderStats(){const acc=allAccuracy();$("statAnswers").textContent=state.answers;$("statAccuracy").textContent=acc===null?"—":acc+"%";$("statCoverage").textContent=coverage()+"%";$("statMastery").textContent=globalMastery()+"%";$("statKnown").textContent=BANK.filter(x=>mastery(x)>=70).length+"/50";$("statSessions").textContent=state.sessions;$("statsFocus").innerHTML=focusHtml(focusItems(8));$("statsConfusions").innerHTML=confusionRows();}
function goHome(){clearInterval(timerHandle);session=null;current=null;renderHome();showScreen("startScreen");}
$("startBtn").addEventListener("click",startSession);$("nextBtn").addEventListener("click",startSession);$("homeBtn").addEventListener("click",goHome);$("endHomeBtn").addEventListener("click",goHome);$("quitBtn").addEventListener("click",goHome);
$("statsBtn").addEventListener("click",()=>{renderStats();showScreen("statsScreen");});$("statsHomeBtn").addEventListener("click",goHome);
document.addEventListener("visibilitychange",()=>{if(document.hidden&&timerHandle)clearInterval(timerHandle);else if(!document.hidden&&session&&!locked&&current){deadline=Date.now()+Math.min(TIME_LIMIT,Number($("timerText").textContent)||TIME_LIMIT)*1000;timerHandle=setInterval(tick,100);}});
renderHome();showScreen("startScreen");