const APP_VERSION="0.3.0",STORAGE_KEY="adaptive_phrasal_verbs_v1",SESSION_SIZE=15,TIME_LIMIT=10;
const BANK=window.PHRASAL_BANK||[],BY_ID=Object.fromEntries(BANK.map(x=>[x.id,x])),PERSONAL_PRIORITY=new Set(["split_up"]);
const MODES=["context","meaning","contrast","particle","paraphrase"];
const TRANSFORMS={
bring_up:"She MENTIONED THE ISSUE during the meeting.",call_off:"They CANCELLED THE MATCH because of the storm.",carry_out:"The team CONDUCTED THE INVESTIGATION carefully.",catch_up_with:"He walked faster to REACH THE OTHERS.",come_across:"I FOUND THE ARTICLE BY CHANCE while browsing.",
come_up_with:"We need to THINK OF A BETTER SOLUTION.",end_up:"We FINALLY FOUND OURSELVES paying much more than expected.",find_out:"I need to DISCOVER what time the museum closes.",get_by:"He MANAGES WITH VERY LITTLE MONEY each month.",get_over:"It took her weeks to RECOVER FROM the illness.",
get_rid_of:"We should REMOVE these old files.",give_in:"After hours of pressure, he finally STOPPED RESISTING.",give_up:"She STOPPED SMOKING last year.",hand_in:"You must SUBMIT your assignment by Friday.",keep_up_with:"I can't STAY AT THE SAME PACE AS the rest of the class.",
look_into:"The council promised to INVESTIGATE the complaint.",put_off:"They POSTPONED the meeting until Monday.",put_up_with:"I can't TOLERATE this noise any longer.",run_out_of:"We HAVE NO MILK LEFT.",set_up:"She ESTABLISHED her own business.",
stick_to:"Try to FOLLOW THE PLAN until the end.",take_over:"A new manager will ASSUME CONTROL OF the department.",take_part_in:"Hundreds of students PARTICIPATED IN the survey.",take_up:"She STARTED PHOTOGRAPHY as a hobby.",turn_out:"The exam PROVED TO BE easier than expected.",work_out:"We need to SOLVE the problem before Friday."
};
let state=loadState(),session=null,current=null,timerHandle=null,deadline=0,locked=false,audioCtx=null,soundOn=true,lastTickShown=TIME_LIMIT+1,lastUrgentBeat=-1,flashQueue=[],flashIndex=0,flashRevealed=false;
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function blankMode(){return{attempts:0,correct:0};}
function blankItem(){return{attempts:0,correct:0,totalTime:0,avgTime:0,streak:0,bestStreak:0,lastSeen:0,misses:0,automatic:0,modes:Object.fromEntries(MODES.map(m=>[m,blankMode()]))};}
function freshState(){return{version:2,level:1,sessions:0,answers:0,correct:0,studySec:0,items:{},confusions:{},history:[],answerHistory:[]};}
function normalizeItem(raw={}){const m=Object.assign(blankItem(),raw);m.modes=m.modes||{};for(const mode of MODES)m.modes[mode]=Object.assign(blankMode(),m.modes[mode]||{});m.automatic=Number(m.automatic)||0;return m;}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")||freshState();s.version=2;s.studySec=Number(s.studySec)||0;s.answerHistory=Array.isArray(s.answerHistory)?s.answerHistory:[];s.history=Array.isArray(s.history)?s.history:[];s.confusions=s.confusions||{};s.items=s.items||{};for(const x of BANK)s.items[x.id]=normalizeItem(s.items[x.id]);return Object.assign(freshState(),s);}catch(e){const s=freshState();for(const x of BANK)s.items[x.id]=blankItem();return s;}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function stats(x){return state.items[x.id]||(state.items[x.id]=blankItem());}
function modeBreadth(x){const m=stats(x);return MODES.filter(k=>m.modes[k]?.attempts>0).length;}
function mastery(x){const m=stats(x);if(!m.attempts)return 0;const acc=m.correct/m.attempts,exp=Math.min(1,m.attempts/10),speed=clamp((TIME_LIMIT-m.avgTime)/TIME_LIMIT,0,1),streak=Math.min(1,m.streak/4),breadth=Math.min(1,modeBreadth(x)/4);return Math.round((acc*.45+exp*.15+speed*.10+streak*.10+breadth*.20)*100);}
function mastered(x){const m=stats(x);return m.attempts>=6&&modeBreadth(x)>=3&&mastery(x)>=75;}
function globalMastery(){return BANK.length?Math.round(BANK.reduce((n,x)=>n+mastery(x),0)/BANK.length):0;}
function coverage(){return BANK.length?Math.round(BANK.filter(x=>stats(x).attempts>0).length/BANK.length*100):0;}
function recentAnswers(n=60){return state.answerHistory.slice(-n);}
function recentAccuracy(){const h=recentAnswers();return h.length?Math.round(h.filter(x=>x.ok).length/h.length*100):null;}
function allAccuracy(){return state.answers?Math.round(state.correct/state.answers*100):null;}
function automaticPct(){const h=recentAnswers();return h.length?Math.round(h.filter(x=>x.ok&&x.time<=4).length/h.length*100):0;}
function avgResponse(){const h=recentAnswers();return h.length?h.reduce((n,x)=>n+x.time,0)/h.length:null;}
function avgHits(){if(!state.sessions)return null;const h=state.history.slice(-20);return h.length?(h.reduce((n,x)=>n+x.score,0)/h.length):null;}
function rating(){const a=recentAccuracy()??allAccuracy()??0;return Math.round(globalMastery()*.55+a*.30+automaticPct()*.15);}
function focusItems(limit=5){const seen=BANK.filter(x=>stats(x).attempts).sort((a,b)=>mastery(a)-mastery(b)||stats(b).misses-stats(a).misses);const unseen=BANK.filter(x=>!stats(x).attempts);return [...seen,...unseen].slice(0,limit);}
function fmtTime(s){s=Math.round(s||0);if(s<60)return s+"s";const m=Math.floor(s/60),r=s%60;return m+"m "+r+"s";}
function hexRgb(hex){const h=hex.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)].join(",");}
function applyTheme(){const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[];if(!ranks.length)return;const i=clamp(Math.ceil((Math.max(1,rating())/100)*15),1,15)-1,rank=ranks[i];document.documentElement.style.setProperty("--ai-color",rank.color);document.documentElement.style.setProperty("--ai-rgb",hexRgb(rank.color));document.documentElement.style.setProperty("--ambient-rank-color",rank.color);}
function showScreen(id){for(const x of ["startScreen","statsScreen","flashScreen","gameScreen","endScreen","errorsScreen"])$(x).classList.toggle("hidden",x!==id);window.scrollTo(0,0);}
function focusPanelHtml(items){const first=items[0];if(!first)return"";const p=mastery(first),rest=items.slice(1,4).map(x=>x.pv+" "+mastery(x)+"%").join(" · ");return '<div class="focus-head"><div><span>FOCUS NOW</span><strong>'+first.pv+' <small>'+p+'%</small></strong></div><em>'+modeBreadth(first)+'/5 MODES</em></div><div class="focus-progress"><i style="width:'+p+'%"></i><span class="focus-mark rec" style="left:75%"></span></div><div class="focus-targets"><span>WEAK</span><span>MASTERED 75%</span></div><p class="focus-why">'+first.en+(rest?'<br>Next: '+rest:'')+'</p>';}
function skillRows(items){return items.map(x=>'<div class="skillrow"><div class="name"><span class="skill-name-text">'+x.pv+'</span></div><div class="track"><div class="fill" style="width:'+mastery(x)+'%"></div></div><div class="pct">'+mastery(x)+'%</div></div>').join("");}
function renderHome(){applyTheme();$("startLevel").textContent="LEVEL "+state.level;$("coverageText").textContent=BANK.filter(x=>stats(x).attempts).length+" / 50";$("coverageFill").style.width=coverage()+"%";$("masteryText").textContent=globalMastery()+"%";$("masteryFill").style.width=globalMastery()+"%";$("startRating").textContent=rating();$("startAccuracy").textContent=(recentAccuracy()??"—")+(recentAccuracy()===null?"":"%");$("startAvg").textContent=avgResponse()===null?"—":avgResponse().toFixed(1)+"s";$("startAllAccuracy").textContent=avgHits()===null?"—":avgHits().toFixed(1);$("startAuto").textContent=automaticPct()+"%";$("startMastered").textContent=BANK.filter(mastered).length+"/50";$("startTotal").textContent=state.answers;$("startStudyTime").textContent=fmtTime(state.studySec);$("startFocusPanel").innerHTML=focusPanelHtml(focusItems());const unseen=BANK.filter(x=>!stats(x).attempts).length;$("campaignStatus").textContent=unseen?unseen+" unseen · English-only from the first question. Easy recognition is phased out as evidence grows.":"All 50 exposed · the engine now prioritises close contrasts, particles and Cambridge paraphrase.";}
function confusionRows(limit=8){const rows=Object.entries(state.confusions).sort((a,b)=>b[1]-a[1]).slice(0,limit);if(!rows.length)return'<div class="statusbox">No stable confusion pair yet.</div>';return rows.map(([key,n])=>{const[a,b]=key.split("|"),A=BY_ID[a],B=BY_ID[b];return A&&B?'<div class="skillrow"><div class="name"><span class="skill-name-text">'+A.pv+' ↔ '+B.pv+'</span></div><div class="track"><div class="fill" style="width:'+Math.min(100,n*15)+'%"></div></div><div class="pct">'+n+'×</div></div>':"";}).join("");}
function renderStats(){applyTheme();$("statsCoverage").textContent=coverage()+"%";$("statsMastery").textContent=globalMastery()+"%";$("statsAccuracy").textContent=(recentAccuracy()??0)+"%";$("statsAllAccuracy").textContent=avgHits()===null?"—":avgHits().toFixed(1);$("statsAutomatic").textContent=automaticPct()+"%";$("statsAvg").textContent=avgResponse()===null?"—":avgResponse().toFixed(1)+"s";$("statsTotal").textContent=state.answers;$("statsStudyTime").textContent=fmtTime(state.studySec);$("statsFocusPanel").innerHTML=focusPanelHtml(focusItems());$("statsConfusions").innerHTML=confusionRows();$("statsSkills").innerHTML=skillRows([...BANK].sort((a,b)=>mastery(a)-mastery(b)));}
function weightFor(x){const m=stats(x),weak=(100-mastery(x))/14,unseen=m.attempts?0:6,miss=Math.min(5,m.misses*.45),breadth=(5-modeBreadth(x))*.8,personal=PERSONAL_PRIORITY.has(x.id)?1.5:0;return 1+weak+unseen+miss+breadth+personal;}
function pickWeighted(pool){const ws=pool.map(weightFor),sum=ws.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<pool.length;i++){r-=ws[i];if(r<=0)return pool[i];}return pool[pool.length-1];}
function buildQueue(){const pool=[...BANK],out=[];while(out.length<SESSION_SIZE&&pool.length){const x=pickWeighted(pool);out.push(x);pool.splice(pool.indexOf(x),1);}return out;}
function chooseMode(x){const m=stats(x),unseen=m.attempts<2,r=Math.random(),lvl=state.level;if(unseen)return r<.50?"context":r<.78?"meaning":r<.90?"particle":"contrast";if(lvl<=3)return r<.38?"context":r<.58?"meaning":r<.77?"particle":r<.92?"contrast":"paraphrase";if(lvl<=7)return r<.26?"context":r<.39?"meaning":r<.61?"particle":r<.84?"contrast":"paraphrase";return r<.18?"context":r<.27?"meaning":r<.52?"particle":r<.78?"contrast":"paraphrase";}
function confusionBonus(target,candidate){return (state.confusions[target.id+"|"+candidate.id]||0)*3+(state.confusions[candidate.id+"|"+target.id]||0)*2;}
function rankedDistractors(target,mode){const base=target.pv.split(" ")[0];return BANK.filter(x=>x.id!==target.id).map(x=>{let score=Math.random()*1.5;if(x.pv.split(" ")[0]===base)score+=mode==="contrast"||mode==="particle"?16:9;if(x.tag===target.tag)score+=7;if(x.difficulty===target.difficulty)score+=1.5;score+=confusionBonus(target,x);return{x,score};}).sort((a,b)=>b.score-a.score).map(o=>o.x);}
function pickDistractors(target,mode,count=3){const ranked=rankedDistractors(target,mode),top=ranked.slice(0,Math.min(10,ranked.length)),out=[];while(out.length<count&&top.length){const span=Math.min(5,top.length),i=Math.floor(Math.random()*span);out.push(top.splice(i,1)[0]);}return out;}
function particleOf(x){return x.pv.split(" ").slice(1).join(" ");}
function particleOptions(target){const base=target.pv.split(" ")[0],same=BANK.filter(x=>x.id!==target.id&&x.pv.split(" ")[0]===base).map(particleOf),fallback=["up","out","off","on","over","back","in","into","with","for","after","by","about","across"];const correct=particleOf(target),pool=[...new Set([...same,...fallback].filter(x=>x&&x!==correct))];return shuffle([correct,...shuffle(pool).slice(0,3)]);}
function contextFor(x,index){const m=stats(x);return x.contexts[(m.attempts+index)%x.contexts.length];}
function makeQuestion(target,index){let mode=chooseMode(target);if(mode==="paraphrase"&&!TRANSFORMS[target.id])mode="contrast";const ds=pickDistractors(target,mode),ctx=contextFor(target,index);if(mode==="meaning"){const full=ctx.replace("___",target.pv.toUpperCase());return{target,mode,text:full+"\nWhat does the phrasal verb mean?",correctKey:target.id,options:shuffle([{key:target.id,text:target.en,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.en,confusionId:x.id}))])};}
if(mode==="particle"){const base=target.pv.split(" ")[0],correct=particleOf(target),opts=particleOptions(target);return{target,mode,text:ctx.replace("___",base+" ___"),correctKey:correct,options:opts.map(x=>({key:x,text:x,confusionId:null}))};}
if(mode==="paraphrase"){return{target,mode,text:"Which phrasal verb best replaces the CAPITALISED idea?\n"+TRANSFORMS[target.id],correctKey:target.id,options:shuffle([{key:target.id,text:target.pv,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.pv,confusionId:x.id}))])};}
return{target,mode,text:ctx,correctKey:target.id,options:shuffle([{key:target.id,text:target.pv,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.pv,confusionId:x.id}))])};}
async function startSession(){await ensureAudio();session={queue:buildQueue(),index:0,correct:0,times:[],errors:[],started:Date.now(),snapshot:JSON.stringify(state)};$("sessionLevel").textContent="L"+state.level;showScreen("gameScreen");renderSegments();nextQuestion();}
function renderSegments(){const box=$("segments");box.innerHTML="";for(let i=0;i<SESSION_SIZE;i++){const d=document.createElement("div");d.className="seg"+(session&&i<session.index?" on":"");box.appendChild(d);}}
function nextQuestion(){clearInterval(timerHandle);locked=false;lastTickShown=TIME_LIMIT+1;lastUrgentBeat=-1;$("correctReveal").classList.remove("show");if(!session||session.index>=SESSION_SIZE){finishSession();return;}current=makeQuestion(session.queue[session.index],session.index);$("qIndex").textContent=session.index+1;$("questionText").textContent=current.text;const box=$("answers");box.innerHTML="";current.options.forEach(o=>{const b=document.createElement("button");b.className="answer";b.textContent=o.text;b.dataset.key=o.key;b.addEventListener("click",()=>answer(o));box.appendChild(b);});deadline=Date.now()+TIME_LIMIT*1000;tick();timerHandle=setInterval(tick,50);}
function audioSupported(){return !!(window.AudioContext||window.webkitAudioContext);}
async function ensureAudio(){
  try{
    const AC=window.AudioContext||window.webkitAudioContext;
    if(!AC){soundOn=false;refreshSoundButton();return false;}
    if(!audioCtx)audioCtx=new AC();
    if(audioCtx.state==='suspended')await audioCtx.resume();
    const ok=audioCtx.state==='running';if(!ok){soundOn=false;refreshSoundButton();}return ok;
  }catch(e){console.warn("Audio unavailable",e);soundOn=false;refreshSoundButton();return false;}
}
function tone(freq,dur=.035,gain=.018,type='sine',delay=0){
  if(!soundOn||!audioCtx||audioCtx.state!=='running')return;
  const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();
  o.type=type;o.frequency.setValueAtTime(freq,t);
  g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.01);
}
function playTick(strong=false,step=0){const f=strong?(step%2?1540:1260):(step%2?1280:980);tone(f,strong?.034:.026,strong?.026:.016,'square');}
function playUrgentTimerPulse(left,beat=0){const final=left<=2,f=final?(beat%2?1660:1450):(beat%2?1360:1160);tone(f,final?.034:.028,final?.016:.012,final?'square':'triangle');if(left<=.55)tone(1960,.042,.010,'sine',.014);}
function playCorrect(){const notes=[440,587.33,783.99,1046.5];notes.forEach((f,i)=>{tone(f,i===3?.11:.052,i===3?.024:.020,i%2?'sine':'triangle',i*.047);if(i>0)tone(f*2,.032,.007,'sine',i*.047+.012);});}
function playWrong(){tone(311.13,.050,.020,'triangle');tone(220,.070,.017,'sine',.042);}
const LEVEL_SCORE_ROOTS=[146.83,155.56,164.81,174.61,196.00,220.00,246.94,261.63,293.66,329.63,349.23,392.00,440.00,493.88,523.25];
function semitoneHz(root,n){return root*Math.pow(2,n/12);}
function playLevelScore(correct,total=15){
  const rank=Math.max(1,Math.min(15,Math.round(15*(Number(correct)||0)/Math.max(1,Number(total)||15)))),root=LEVEL_SCORE_ROOTS[rank-1];
  let intervals=[0],step=.105,dur=.085,gain=.015,type='triangle';
  if(rank<=3){intervals=[0,-1,-5];step=.11;dur=.11;gain=.014;type='triangle';}
  else if(rank<=6){intervals=[0,3,0];step=.095;dur=.095;gain=.015;type='sine';}
  else if(rank<=9){intervals=[0,2,4];step=.085;dur=.085;gain=.017;type='triangle';}
  else if(rank<=12){intervals=[0,4,7,12];step=.075;dur=.09;gain=.019;type='triangle';}
  else if(rank<=14){intervals=[0,4,7,12,16];step=.068;dur=.095;gain=.021;type='sine';}
  else{intervals=[0,4,7,12,16,19,24];step=.062;dur=.105;gain=.024;type='triangle';}
  intervals.forEach((semi,i)=>{const delay=i*step,f=semitoneHz(root,semi);tone(f,i===intervals.length-1?dur*1.8:dur,gain,type,delay);if(rank>=10&&i>=2)tone(f*2,.045,gain*.24,'sine',delay+.012);});
  if(rank>=13){const finale=(intervals.length-1)*step+.07;tone(root/2,.22,gain*.8,'sine',finale);[0,4,7,12].forEach((semi,i)=>tone(semitoneHz(root,semi),rank===15?.28:.20,gain*(rank===15?.72:.55),i%2?'sine':'triangle',finale+i*.012));}
  if(rank===15){const crown=(intervals.length-1)*step+.30;[12,16,19,24].forEach((semi,i)=>tone(semitoneHz(root,semi),.18,.012,'sine',crown+i*.045));}
}
function haptic(ok){try{if(navigator.vibrate)navigator.vibrate(ok?18:[24,16,42]);}catch(e){}}
function pulseFeedback(ok){const cls=ok?"feedback-correct":"feedback-wrong";document.body.classList.remove("feedback-correct","feedback-wrong");void document.body.offsetWidth;document.body.classList.add(cls);setTimeout(()=>document.body.classList.remove(cls),430);}
function burstParticles(anchor){if(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const layer=$("particles");if(!layer)return;const r=anchor&&anchor.getBoundingClientRect?anchor.getBoundingClientRect():null,cx=r?r.left+r.width/2:innerWidth/2,cy=r?r.top+r.height/2:innerHeight*.55,colors=["#E7BF57","#BB9EF0","#7AA5EC","#4AA7C8","#57965A"];for(let i=0;i<6;i++){const p=document.createElement("i"),a=(Math.PI*2*i/6)+(Math.random()-.5)*.28,d=26+Math.random()*42;p.className="particle";p.style.left=cx+"px";p.style.top=cy+"px";p.style.setProperty("--dx",Math.cos(a)*d+"px");p.style.setProperty("--dy",Math.sin(a)*d+"px");p.style.setProperty("--rot",Math.round((Math.random()-.5)*180)+"deg");p.style.setProperty("--size",(4+Math.random()*4)+"px");p.style.setProperty("--delay",Math.round(Math.random()*70)+"ms");p.style.setProperty("--particle-color",colors[i%colors.length]);layer.appendChild(p);setTimeout(()=>p.remove(),460);}}
function refreshSoundButton(){const b=$("soundBtn");if(!b)return;if(!audioSupported()){soundOn=false;b.disabled=true;b.textContent='🔇';b.setAttribute('aria-label','Audio unavailable');b.title='Audio unavailable';return;}b.disabled=false;b.textContent=soundOn?'🔊':'🔇';b.setAttribute('aria-label',soundOn?'Sound on':'Sound off');b.title='';}
function tick(){const ms=Math.max(0,deadline-Date.now()),sec=ms/1000,pct=ms/(TIME_LIMIT*1000)*100,shown=Math.ceil(sec);$("timerText").textContent=sec.toFixed(1);$("timer").style.setProperty("--timer-cut",(100-pct)+"%");$("timer").classList.toggle("urgent",sec<=3);if(sec>3&&shown<lastTickShown&&shown>0&&shown<TIME_LIMIT){playTick(false,shown);lastTickShown=shown;}if(sec<=3&&sec>0){const beat=sec>2?Math.floor((3-sec)*2):100+Math.floor((2-sec)*4);if(beat!==lastUrgentBeat){lastUrgentBeat=beat;playUrgentTimerPulse(sec,beat);}}if(ms<=0){clearInterval(timerHandle);answer(null,true);}}
function showCorrectReveal(target){const pos=Math.max(1,current.options.findIndex(o=>o.key===current.correctKey)+1);const el=$("correctReveal");el.className="correct-reveal show pos-"+pos;el.innerHTML='<div class="correct-reveal-kicker"><i></i>CORRECT ANSWER</div><strong>'+target.pv+'</strong>';}
function answer(option,timeout=false){if(locked)return;locked=true;clearInterval(timerHandle);const elapsed=clamp((TIME_LIMIT*1000-Math.max(0,deadline-Date.now()))/1000,0,TIME_LIMIT),target=current.target,ok=!!option&&option.key===current.correctKey,m=stats(target),mm=m.modes[current.mode];m.attempts++;m.totalTime+=elapsed;m.avgTime=m.totalTime/m.attempts;m.lastSeen=Date.now();mm.attempts++;state.answers++;state.studySec+=elapsed;if(ok){m.correct++;m.streak++;m.bestStreak=Math.max(m.bestStreak,m.streak);mm.correct++;state.correct++;session.correct++;if(elapsed<=4)m.automatic++;}else{m.streak=0;m.misses++;let wrongId=option?.confusionId||null;if(!wrongId&&option&&current.mode==="particle"){const base=target.pv.split(" ")[0],cand=BANK.find(x=>x.id!==target.id&&x.pv.split(" ")[0]===base&&particleOf(x)===option.key);wrongId=cand?.id||null;}if(wrongId){const key=target.id+"|"+wrongId;state.confusions[key]=(state.confusions[key]||0)+1;}session.errors.push({target:target.id,choice:wrongId,shown:option?.text||null,timeout,mode:current.mode,question:current.text});}
state.answerHistory.push({id:target.id,mode:current.mode,ok,time:elapsed,at:Date.now()});state.answerHistory=state.answerHistory.slice(-1200);session.times.push(elapsed);const buttons=[...$("answers").children];buttons.forEach(b=>{b.disabled=true;if(b.dataset.key===current.correctKey)b.classList.add("good");else if(option&&b.dataset.key===option.key)b.classList.add("bad");else b.classList.add("dim");});if(!ok)showCorrectReveal(target);showFeedback(ok,timeout,target);try{if(ok)playCorrect();else playWrong();haptic(ok);pulseFeedback(ok);if(ok&&option){const chosen=buttons.find(b=>b.dataset.key===option.key);if(chosen)burstParticles(chosen);}}catch(e){console.warn("Feedback audio unavailable",e);}save();setTimeout(()=>{session.index++;renderSegments();nextQuestion();},ok?555:1050);}
function showFeedback(ok,timeout,target){const f=$("feedback");f.className="feedback "+(ok?"ok":"no");f.innerHTML='<div class="feedback-label">'+(ok?"CORRECT":timeout?"TIME":"NOT QUITE")+'</div><div class="appearance">'+target.pv+'</div><small>'+target.en+'</small>';requestAnimationFrame(()=>f.classList.add("show"));setTimeout(()=>f.classList.remove("show"),560);}
function finishSession(){clearInterval(timerHandle);const acc=session.correct/SESSION_SIZE,old=state.level;if(acc>=.80)state.level=Math.min(15,state.level+1);else if(acc<.47)state.level=Math.max(1,state.level-1);state.sessions++;state.history.push({at:Date.now(),score:session.correct,total:SESSION_SIZE,levelBefore:old,levelAfter:state.level,avgTime:session.times.reduce((a,b)=>a+b,0)/session.times.length});state.history=state.history.slice(-400);save();playLevelScore(session.correct,SESSION_SIZE);renderEnd(old);showScreen("endScreen");}
function lessonItem(){if(session.errors.length)return BY_ID[session.errors[0].target];return [...session.queue].sort((a,b)=>mastery(a)-mastery(b))[0];}
function renderLesson(){const x=lessonItem();if(!x){$("levelLesson").classList.add("hidden");return;}const example=x.contexts[0].replace("___",x.pv);$("levelLesson").classList.remove("hidden");$("levelLesson").innerHTML='<div class="lesson-kicker">LEVEL FLASHCARD · ENGLISH ONLY</div><h2>'+x.pv+'</h2><div class="lesson-source"><b>Meaning:</b> '+x.en+'</div><div class="lesson-formula">'+x.pv.toUpperCase()+'</div><div class="lesson-example"><strong>Example</strong>'+example+'</div><div class="lesson-cue">Mastery '+mastery(x)+'% · '+modeBreadth(x)+'/5 exercise modes seen.</div>';}
function renderEnd(old){applyTheme();const acc=Math.round(session.correct/SESSION_SIZE*100),avg=session.times.reduce((a,b)=>a+b,0)/session.times.length;$("endScore").textContent=session.correct+"/15";$("endSub").textContent=state.level>old?"Level up · harder contrasts unlocked.":state.level<old?"Level adjusted · weak contrasts recycled.":"Level held · difficulty rebalanced.";$("eAvg").textContent=avg.toFixed(1)+"s";$("eAuto").textContent=automaticPct()+"%";$("eRating").textContent=rating();$("eCoverage").textContent=coverage()+"%";$("eMastery").textContent=globalMastery()+"%";$("eMastered").textContent=BANK.filter(mastered).length+"/50";$("weakSkills").innerHTML=skillRows(focusItems());const has=session.errors.length>0;for(const id of ["errorsBtn","topErrorsBtn"])$(id).classList.toggle("hidden",!has);renderLesson();}
function renderErrors(){const box=$("errorsFull");$("errorsCount").textContent=session?.errors?.length?session.errors.length+" mistakes in the latest level.":"No mistakes in the latest level.";if(!session?.errors?.length){box.innerHTML='<div class="statusbox">Perfect level.</div>';return;}box.innerHTML=session.errors.map(e=>{const t=BY_ID[e.target],c=e.choice?BY_ID[e.choice]:null;return '<div class="mistake-card"><b>'+t.pv+' · '+e.mode.toUpperCase()+'</b><p>'+e.question+'</p><div class="mistake-choice"><div>'+(e.timeout?"TIME":e.shown?("Your answer: "+e.shown):"Wrong answer")+'</div><div class="correct">Correct: '+t.pv+' · '+t.en+'</div></div>'+(c?'<p>Confused with <strong>'+c.pv+'</strong>: '+c.en+'</p>':'')+'</div>';}).join("");}
function openErrors(){renderErrors();showScreen("errorsScreen");}
function renderFlash(){const x=flashQueue[flashIndex%flashQueue.length];if(!x)return;flashRevealed=false;$("flashAgainBtn").textContent="SHOW ANSWER";const example=x.contexts[0];$("flashCardHost").innerHTML='<div class="lesson-kicker">CARD '+(flashIndex+1)+' / '+flashQueue.length+' · MASTERY '+mastery(x)+'%</div><h2>Which phrasal verb?</h2><div class="lesson-source"><b>Meaning:</b> '+x.en+'</div><div class="lesson-example"><strong>Context</strong>'+example+'</div><div id="flashReveal" class="lesson-formula hidden">'+x.pv.toUpperCase()+'</div><div class="lesson-cue">'+modeBreadth(x)+'/5 exercise modes seen · '+stats(x).attempts+' adaptive attempts.</div>';}
function openFlash(){flashQueue=[...BANK].sort((a,b)=>mastery(a)-mastery(b)||stats(a).attempts-stats(b).attempts);flashIndex=0;renderFlash();showScreen("flashScreen");}
function toggleFlash(){flashRevealed=!flashRevealed;$("flashReveal").classList.toggle("hidden",!flashRevealed);$("flashAgainBtn").textContent=flashRevealed?"HIDE ANSWER":"SHOW ANSWER";}
function nextFlash(){flashIndex=(flashIndex+1)%flashQueue.length;renderFlash();}
function goHome(){clearInterval(timerHandle);session=null;current=null;renderHome();showScreen("startScreen");}
function abortSession(){clearInterval(timerHandle);if(session?.snapshot){state=JSON.parse(session.snapshot);for(const x of BANK)state.items[x.id]=normalizeItem(state.items[x.id]);save();}goHome();}
async function setSound(){soundOn=!soundOn;if(soundOn){await ensureAudio();tone(760,.06,.025,"sine");}refreshSoundButton();}
$("startBtn").addEventListener("click",startSession);$("continueBtn").addEventListener("click",startSession);$("topContinueBtn").addEventListener("click",startSession);$("homeBtn").addEventListener("click",goHome);$("topHomeBtn").addEventListener("click",goHome);$("abortSessionBtn").addEventListener("click",abortSession);$("soundBtn").addEventListener("click",setSound);
$("statsBtn").addEventListener("click",()=>{renderStats();showScreen("statsScreen");});$("statsBackBtn").addEventListener("click",goHome);$("statsTopDashboardBtn").addEventListener("click",goHome);
$("flashBtn").addEventListener("click",openFlash);$("flashAgainBtn").addEventListener("click",toggleFlash);$("flashNextBtn").addEventListener("click",nextFlash);$("flashBackBtn").addEventListener("click",goHome);$("flashTopDashboardBtn").addEventListener("click",goHome);
$("errorsBtn").addEventListener("click",openErrors);$("topErrorsBtn").addEventListener("click",openErrors);$("errorsBackBtn").addEventListener("click",()=>showScreen("endScreen"));$("errorsTopDashboardBtn").addEventListener("click",goHome);
document.addEventListener("visibilitychange",()=>{if(document.hidden&&timerHandle)clearInterval(timerHandle);else if(!document.hidden&&session&&!locked&&current){deadline=Date.now()+Math.min(TIME_LIMIT,parseFloat($("timerText").textContent)||TIME_LIMIT)*1000;lastTickShown=Math.ceil(parseFloat($("timerText").textContent)||TIME_LIMIT)+1;lastUrgentBeat=-1;timerHandle=setInterval(tick,50);}});
refreshSoundButton();renderHome();showScreen("startScreen");