const APP_VERSION="0.5.1",STORAGE_KEY="adaptive_phrasal_verbs_v1",SESSION_SIZE=15,TIME_LIMIT=15;
const BANK=window.PHRASAL_BANK||[],BY_ID=Object.fromEntries(BANK.map(x=>[x.id,x])),PERSONAL_PRIORITY=new Set(["split_up"]);
const MODES=["context","meaning","contrast","particle","paraphrase"];
const AVS_RANKS=window.ADRIAN_VISUAL_SYSTEM?.ranks||[];
const COLOR_BANDS_15=AVS_RANKS.length?AVS_RANKS.map(x=>x.color):["#422522","#512927","#632D2A","#762F32","#843729","#904311","#90570C","#8B6B05","#798136","#57965A","#32A48F","#4AA7C8","#7AA5EC","#BB9EF0","#E7BF57"];
const AVS_TEXT_BANDS_15=AVS_RANKS.length?AVS_RANKS.map(x=>x.text||x.color):COLOR_BANDS_15;
const TRANSFORMS={
bring_up:"She MENTIONED the issue.",call_off:"They CANCELLED the match.",carry_out:"They PERFORMED the test.",catch_up_with:"He REACHED the others.",come_across:"I FOUND it by chance.",
come_up_with:"We INVENTED a solution.",end_up:"We FINALLY got lost.",find_out:"I DISCOVERED the truth.",get_by:"He MANAGES on little money.",get_over:"She RECOVERED from flu.",
get_rid_of:"We REMOVED the old files.",give_in:"He STOPPED RESISTING.",give_up:"She STOPPED smoking.",hand_in:"SUBMIT your work.",keep_up_with:"I can't MATCH their pace.",
look_into:"They INVESTIGATED the complaint.",put_off:"They POSTPONED the meeting.",put_up_with:"I can't TOLERATE this noise.",run_out_of:"We HAVE NO milk left.",set_up:"She ESTABLISHED a business.",
stick_to:"FOLLOW the plan.",take_over:"She ASSUMED CONTROL.",take_part_in:"He PARTICIPATED in the survey.",take_up:"She STARTED yoga.",turn_out:"It PROVED easy.",work_out:"We SOLVED the problem."
};
let state=loadState(),session=null,current=null,timerHandle=null,deadline=0,locked=false,audioCtx=null,soundOn=true,lastTickShown=TIME_LIMIT+1,lastUrgentBeat=-1,flashQueue=[],flashIndex=0,flashRevealed=false;
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function blankMode(){return{attempts:0,correct:0};}
function blankItem(){return{attempts:0,correct:0,totalTime:0,avgTime:0,streak:0,bestStreak:0,lastSeen:0,misses:0,automatic:0,modes:Object.fromEntries(MODES.map(m=>[m,blankMode()]))};}
function freshState(){return{version:2,level:1,sessions:0,answers:0,correct:0,studySec:0,items:{},confusions:{},history:[],answerHistory:[]};}
function normalizeItem(raw={}){const m=Object.assign(blankItem(),raw);m.modes=m.modes||{};for(const mode of MODES)m.modes[mode]=Object.assign(blankMode(),m.modes[mode]||{});m.automatic=Number(m.automatic)||0;return m;}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")||freshState();s.version=2;s.studySec=Number(s.studySec)||0;s.answerHistory=Array.isArray(s.answerHistory)?s.answerHistory:[];s.history=Array.isArray(s.history)?s.history:[];s.confusions=s.confusions||{};s.items=s.items||{};for(const x of BANK)s.items[x.id]=normalizeItem(s.items[x.id]);return Object.assign(freshState(),s);}catch(e){const s=freshState();for(const x of BANK)s.items[x.id]=blankItem();return s;}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function stats(x){return state.items[x.id]||(state.items[x.id]=blankItem());}
function modeBreadth(x){const m=stats(x);return MODES.filter(k=>m.modes[k]?.attempts>0).length;}
function mastery(x){const m=stats(x);if(!m.attempts)return 0;const acc=m.correct/m.attempts,exp=Math.min(1,m.attempts/10),speed=clamp((TIME_LIMIT-m.avgTime)/TIME_LIMIT,0,1),streak=Math.min(1,m.streak/4),breadth=Math.min(1,modeBreadth(x)/4);return Math.round((acc*.45+exp*.15+speed*.10+streak*.10+breadth*.20)*100);}
function mastered(x){const m=stats(x);return m.attempts>=6&&modeBreadth(x)>=3&&mastery(x)>=75;}
function globalMastery(){return BANK.length?Math.round(BANK.reduce((n,x)=>n+mastery(x),0)/BANK.length):0;}
function coverage(){return BANK.length?Math.round(BANK.filter(x=>stats(x).attempts>0).length/BANK.length*100):0;}
function recentAnswers(n=60){return state.answerHistory.slice(-n);}
function recentAccuracy(){const h=recentAnswers();return h.length?Math.round(h.filter(x=>x.ok).length/h.length*100):null;}
function allAccuracy(){return state.answers?Math.round(state.correct/state.answers*100):null;}
function automaticPct(){const h=recentAnswers();return h.length?Math.round(h.filter(x=>x.ok&&x.time<=4).length/h.length*100):0;}
function avgResponse(){const h=recentAnswers();return h.length?h.reduce((n,x)=>n+x.time,0)/h.length:null;}
function avgHits(){if(!state.sessions)return null;const h=state.history.slice(-20);return h.length?(h.reduce((n,x)=>n+x.score,0)/h.length):null;}
function rating(){const a=recentAccuracy()??allAccuracy()??0;return Math.round(globalMastery()*.55+a*.30+automaticPct()*.15);}
function focusItems(limit=5){const seen=BANK.filter(x=>stats(x).attempts).sort((a,b)=>mastery(a)-mastery(b)||stats(b).misses-stats(a).misses);const unseen=BANK.filter(x=>!stats(x).attempts);return [...seen,...unseen].slice(0,limit);}
function fmtTime(s){s=Math.round(s||0);if(s<60)return s+"s";const m=Math.floor(s/60),r=s%60;return m+"m "+r+"s";}
function hexRgb(hex){const h=hex.replace("#","");return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)].join(",");}
function valueLevel(v){return Math.max(1,Math.min(15,Math.ceil(clamp(Number(v)||0,0,1)*15)));}
function valueColor(v){return COLOR_BANDS_15[valueLevel(v)-1];}
function valueTextColor(v){return AVS_TEXT_BANDS_15[valueLevel(v)-1];}
function paintText(id,v){const el=$(id);if(el)el.style.color=valueTextColor(v);}
function paintFill(id,v){const el=$(id);if(el)el.style.background=valueColor(v);}
function paintScore(id,score,max=15){const el=$(id);if(el)el.style.color=valueTextColor(clamp((Number(score)||0)/Math.max(1,Number(max)||15),0,1));}
function applyTheme(){const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[];if(!ranks.length)return;const i=clamp(Math.ceil((Math.max(1,rating())/100)*15),1,15)-1,rank=ranks[i];document.documentElement.style.setProperty("--ai-color",rank.color);document.documentElement.style.setProperty("--ai-rgb",hexRgb(rank.color));document.documentElement.style.setProperty("--ambient-rank-color",rank.color);}
function showScreen(id){for(const x of ["startScreen","statsScreen","flashScreen","gameScreen","endScreen","errorsScreen"])$(x).classList.toggle("hidden",x!==id);window.scrollTo(0,0);}
function localDayKey(ts=Date.now()){const d=new Date(ts),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return y+"-"+m+"-"+day;}
function focusPlan(){return{minimum:8,recommended:12,stretch:18};}
function focusWeekData(){const now=new Date(),dow=(now.getDay()+6)%7,monday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-dow),labels=["L","M","X","J","V","S","D"],map={};for(const x of state.answerHistory||[]){const k=localDayKey(x.at||0);map[k]=(map[k]||0)+(Number(x.time)||0);}return labels.map((label,i)=>{const d=new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+i),key=localDayKey(d.getTime()),future=d>now;return{label,key,today:key===localDayKey(),future,sec:map[key]||0};});}
function focusStatus(mins,t){if(mins>=t.stretch)return"stretch reached";if(mins>=t.recommended)return"recommended met";if(mins>=t.minimum)return"minimum reached";return Math.max(0,Math.ceil(t.minimum-mins))+"m to minimum";}
function focusPanelHtml(items){const t=focusPlan(),days=focusWeekData(),todaySec=days.find(x=>x.today)?.sec||0,todayMin=todaySec/60,totalSec=Number(state.studySec)||0,weekSec=days.reduce((n,x)=>n+x.sec,0),maxMin=Math.max(t.stretch,...days.map(x=>x.sec/60),1),p=Math.min(100,todayMin/t.stretch*100),minPos=t.minimum/t.stretch*100,recPos=t.recommended/t.stretch*100,weak=items?.[0],bars=days.map(d=>{const mins=d.sec/60,h=d.future?0:Math.max(d.sec?4:0,Math.min(100,mins/maxMin*100));return '<div class="focus-day '+(d.today?"today ":"")+(d.future?"future":"")+'"><div class="focus-bar-mini"><i style="height:'+h+'%"></i></div><b>'+d.label+'</b><small>'+(mins?Math.round(mins)+"m":"·")+'</small></div>';}).join("");return '<div class="focus-head"><div><span>FOCUS TIME · TODAY</span><strong>'+fmtTime(todaySec)+' <small>/ '+t.recommended+'m</small></strong></div><em>'+focusStatus(todayMin,t)+'</em></div><div class="focus-progress"><i style="width:'+p+'%"></i><b class="focus-mark min" style="left:'+minPos+'%"></b><b class="focus-mark rec" style="left:'+recPos+'%"></b></div><div class="focus-targets"><span>MIN '+t.minimum+'m</span><span>REC '+t.recommended+'m</span><span>STRETCH '+t.stretch+'m</span></div><p class="focus-why">Base '+t.recommended+'m · adaptive recycling'+(weak?" · weakest: "+weak.pv:"")+'</p><div class="focus-week"><div class="focus-week-head"><b>THIS WEEK · '+fmtTime(weekSec)+'</b><span>TOTAL FOCUS · '+fmtTime(totalSec)+'</span></div><div class="focus-week-bars">'+bars+'</div></div><small class="focus-note">Focus Time counts active answer time recorded by this app.</small>';}
function skillRows(items){return items.map(x=>'<div class="skillrow"><div class="name"><span class="skill-name-text">'+x.pv+'</span></div><div class="track"><div class="fill" style="width:'+mastery(x)+'%"></div></div><div class="pct">'+mastery(x)+'%</div></div>').join("");}
function ratingRank(){return state.answers?clamp(Math.ceil((rating()/100)*15),1,15):0;}
function stageLabel(rank){const names=["FOUNDATIONS","CONTROL","B2 PATTERNS","FLUENCY","AUTOMATICITY","MASTERY"];return names[Math.min(5,Math.max(0,Math.floor(((rank||1)-1)/3)))];}
function evidencePct(){return Math.min(100,Math.round((state.answers/Math.max(1,BANK.length*4))*100));}
function readinessPct(){return Math.round(.45*coverage()+.55*Math.min(100,(globalMastery()/80)*100));}
function focusTodaySec(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();return recentAnswers(1200).filter(x=>(x.at||0)>=start).reduce((n,x)=>n+(Number(x.time)||0),0);}
function renderDailyPhrasal(){const host=$("dailyKeyHost"),x=focusItems(1)[0];if(!host||!x)return;const m=mastery(x),front=x.contexts[0],back=x.contexts[0].replace("___",x.pv);host.innerHTML='<div class="daily-key-head"><div><span>PHRASAL KEY</span><b>WEAKEST CURRENT TARGET</b></div><em>'+m+'%</em></div><div class="key-marks">'+Array.from({length:25},(_,i)=>'<i class="'+(i<Math.round(m/4)?"on":"")+'"></i>').join("")+'</div><button id="dailyPhrasalCard" class="daily-key-card" type="button" aria-expanded="false"><div class="daily-key-face daily-key-front"><small>ENGLISH → ENGLISH</small><strong>'+front+'</strong><span>TAP TO REVEAL</span></div><div class="daily-key-face daily-key-back"><small>PHRASAL UNLOCKED</small><strong>'+x.pv.toUpperCase()+'</strong><b>'+x.en+'</b><span>'+back+'</span></div></button><div class="key-carousel-hint">1 TAP: FLIP · 2nd TAP: HIDE</div>';const card=$("dailyPhrasalCard");card?.addEventListener("click",async()=>{card.classList.toggle("revealed");card.setAttribute("aria-expanded",card.classList.contains("revealed")?"true":"false");try{await ensureAudio();playKeyFlip(card.classList.contains("revealed"),true);}catch(e){}});}
function playKeyFlip(revealed=true,soft=false){const notes=revealed?[[659.25,0],[987.77,.045],[1318.5,.095]]:[[987.77,0],[783.99,.045],[587.33,.09]],gain=soft?.006:.011;notes.forEach(([f,d],i)=>tone(f,i===2?.085:.055,i===2?gain:gain*.82,i===1?"triangle":"sine",d));}
function treeRand(seed=129){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let x=t;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return((x^x>>>14)>>>0)/4294967296;};}
let TREE_PARTS_CACHE=null;
function growthTreeParts(){if(TREE_PARTS_CACHE)return TREE_PARTS_CACHE;const rnd=treeRand(20260912),branches=[],leaves=[];const grow=(x,y,len,ang,width,depth,dist)=>{const sway=(rnd()-.5)*.18,angle=ang+sway,x2=x+Math.cos(angle)*len,y2=y+Math.sin(angle)*len,bend=(rnd()-.5)*10,mx=(x+x2)/2+Math.cos(angle+Math.PI/2)*bend,my=(y+y2)/2+Math.sin(angle+Math.PI/2)*bend,score=dist+len*.58+depth*2+rnd()*2;branches.push({score,html:'<path d="M '+x.toFixed(1)+' '+y.toFixed(1)+' Q '+mx.toFixed(1)+' '+my.toFixed(1)+' '+x2.toFixed(1)+' '+y2.toFixed(1)+'" stroke-width="'+Math.max(1.25,width).toFixed(2)+'"/>'});if(depth>=4){const rot=Math.round((rnd()-.5)*90),rx=(5+rnd()*5).toFixed(1),ry=(2.8+rnd()*3).toFixed(1),green=["#607d3b","#769447","#8ca85a","#526f36"][Math.floor(rnd()*4)];leaves.push({score:score+8+rnd()*15,html:'<ellipse cx="'+(x2+(rnd()-.5)*7).toFixed(1)+'" cy="'+(y2+(rnd()-.5)*6).toFixed(1)+'" rx="'+rx+'" ry="'+ry+'" transform="rotate('+rot+' '+x2.toFixed(1)+' '+y2.toFixed(1)+')" fill="'+green+'"/>'});}if(depth>=6)return;const next=len*(.72+rnd()*.09),w=width*.72,spread=.35+rnd()*.20;grow(x2,y2,next,angle-spread,w,depth+1,dist+len);grow(x2,y2,next*(.92+rnd()*.12),angle+spread*(.88+rnd()*.22),w*.96,depth+1,dist+len);};grow(210,274,56,-Math.PI/2,12,0,0);TREE_PARTS_CACHE=[...branches.map(x=>({...x,kind:"branch"})),...leaves.map(x=>({...x,kind:"leaf"}))].sort((a,b)=>a.score-b.score||a.kind.localeCompare(b.kind)).slice(0,200);return TREE_PARTS_CACHE;}
function renderGrowthTree(){const host=$("growthTreeHost");if(!host)return;const stage=Math.min(200,Math.max(1,Math.round((state.level/15)*200))),parts=growthTreeParts().slice(0,stage),branch=parts.filter(x=>x.kind==="branch").map(x=>x.html).join(""),leaf=parts.filter(x=>x.kind==="leaf").map(x=>x.html).join("");host.innerHTML='<div class="growth-tree-canvas" data-tree-stage="'+stage+'"><svg viewBox="0 0 420 300" role="img" aria-label="Practice tree, growth stage '+stage+' of 200"><defs><linearGradient id="treeTrunk" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#5d3827"/><stop offset=".55" stop-color="#76503a"/><stop offset="1" stop-color="#957258"/></linearGradient></defs><ellipse class="tree-ground" cx="210" cy="282" rx="78" ry="7"/><g class="tree-branches" fill="none" stroke="url(#treeTrunk)" stroke-linecap="round" stroke-linejoin="round">'+branch+'</g><g class="tree-leaves">'+leaf+'</g></svg></div><div class="growth-tree-count"><b>'+state.level.toLocaleString()+'</b><span>LEVEL</span></div>';}
function renderHome(){
  applyTheme();
  const rank=ratingRank(),stageNum=Math.min(6,Math.max(1,Math.ceil((rank||1)/3))),evidence=evidencePct(),ready=readinessPct(),today=focusTodaySec(),seen=BANK.filter(x=>stats(x).attempts).length,pairs=Object.values(state.confusions||{}).filter(n=>n>0).length,recent=recentAccuracy(),all=allAccuracy(),delta=recent!=null&&all!=null?recent-all:null,masteredN=BANK.filter(mastered).length;
  $("startKicker").textContent="CAMPAIGN 1 · STAGE "+stageNum+"/6 · "+stageLabel(rank);
  $("startLevel").textContent="LEVEL "+state.level;
  $("startAiLevel").textContent=(rank?rank:"—")+" / 15";
  $("startAiConfidence").textContent="AI Valoration · evidence "+evidence+"%";
  $("coverageText").textContent=seen.toLocaleString()+" / "+BANK.length.toLocaleString();$("coverageFill").style.width=coverage()+"%";
  $("masteryText").textContent=globalMastery()+"%";$("masteryFill").style.width=globalMastery()+"%";
  $("startRating").textContent=rating()||"—";$("startAccuracy").textContent=recent==null?"—":recent+"%";$("startAvg").textContent=avgResponse()==null?"—":avgResponse().toFixed(1)+"s";$("startAllAccuracy").textContent=avgHits()==null?"—":avgHits().toFixed(1);$("startAuto").textContent=automaticPct()+"%";$("startMastered").textContent=masteredN+"/"+BANK.length;$("startTotal").textContent=state.answers;$("startStudyTime").textContent=fmtTime(state.studySec);
  $("startPhrasalsSeen").textContent=seen;$("startConfusionPairs").textContent=pairs;$("startFocusPanel").innerHTML=focusPanelHtml(focusItems());
  $("startPeerDelta").textContent=delta==null?"—":(delta>=0?"+":"")+delta;$("startPeerDelta").className="peer-delta "+(delta==null||Math.abs(delta)<3?"neutral":delta>0?"good":"bad");
  $("paceRecent").textContent=recent==null?"—":recent;$("paceAll").textContent=all==null?"—":all;$("paceMastery").textContent=globalMastery();$("paceCoverage").textContent=coverage();$("paceAuto").textContent=automaticPct();
  $("startPeerStatus").textContent="Today "+fmtTime(today)+" · "+(state.sessions?state.sessions+" completed levels":"building evidence")+" · English-only adaptive practice";
  $("readinessScore").textContent=ready+"%";$("readinessFill").style.width=ready+"%";$("readinessStage").textContent=ready>=85?"Exam-ready core":ready>=65?"Consolidating":ready>=40?"Building control":"Building foundation";
  $("readinessStatus").textContent="Internal readiness: coverage "+coverage()+"% · mastery "+globalMastery()+"% · target 100% coverage + stable multi-mode mastery.";$("readinessBox").classList.toggle("ready",ready>=85);
  $("readinessCore").textContent=masteredN+" / "+BANK.length+" mastered";$("readinessEvidence").textContent=state.answers+" answers · "+state.sessions+" completed levels";
  const unseen=BANK.length-seen;$("campaignStatus").textContent=unseen?unseen+" unseen · 15 s fixed · short prompts · close distractors.":"All "+BANK.length+" exposed · distractors tighten as your level rises.";
  $("startBtn").textContent=state.sessions?"CONTINUE · LEVEL "+state.level:"START · LEVEL "+state.level;$("buildVersion").textContent=(location.protocol.startsWith("http")?"ONLINE":"LOCAL")+" BUILD · v0.5.0 · BANK "+BANK.length;
  if(rank){$("startAiLevel").style.color=AVS_TEXT_BANDS_15[rank-1];}paintText("coverageText",coverage()/100);paintFill("coverageFill",coverage()/100);paintText("masteryText",globalMastery()/100);paintFill("masteryFill",globalMastery()/100);paintText("startRating",rating()/100);if(recent!=null)paintText("startAccuracy",recent/100);if(avgHits()!=null)paintScore("startAllAccuracy",avgHits());paintText("startAuto",automaticPct()/100);paintText("startMastered",masteredN/BANK.length);paintText("readinessScore",ready/100);paintFill("readinessFill",ready/100);
  renderDailyPhrasal();renderGrowthTree();if(window.AdaptiveLanguageDashboard)window.AdaptiveLanguageDashboard.refresh();
}

function confusionRows(limit=8){const rows=Object.entries(state.confusions).sort((a,b)=>b[1]-a[1]).slice(0,limit);if(!rows.length)return'<div class="statusbox">No stable confusion pair yet.</div>';return rows.map(([key,n])=>{const[a,b]=key.split("|"),A=BY_ID[a],B=BY_ID[b];return A&&B?'<div class="skillrow"><div class="name"><span class="skill-name-text">'+A.pv+' ↔ '+B.pv+'</span></div><div class="track"><div class="fill" style="width:'+Math.min(100,n*15)+'%"></div></div><div class="pct">'+n+'×</div></div>':"";}).join("");}
function renderStats(){applyTheme();$("statsCoverage").textContent=coverage()+"%";$("statsMastery").textContent=globalMastery()+"%";$("statsAccuracy").textContent=(recentAccuracy()??0)+"%";$("statsAllAccuracy").textContent=avgHits()===null?"—":avgHits().toFixed(1);$("statsAutomatic").textContent=automaticPct()+"%";$("statsAvg").textContent=avgResponse()===null?"—":avgResponse().toFixed(1)+"s";$("statsTotal").textContent=state.answers;$("statsStudyTime").textContent=fmtTime(state.studySec);$("statsFocusPanel").innerHTML=focusPanelHtml(focusItems());$("statsConfusions").innerHTML=confusionRows();$("statsSkills").innerHTML=skillRows([...BANK].sort((a,b)=>mastery(a)-mastery(b)));}
function weightFor(x){const m=stats(x),weak=(100-mastery(x))/14,unseen=m.attempts?0:6,miss=Math.min(5,m.misses*.45),breadth=(5-modeBreadth(x))*.8,personal=PERSONAL_PRIORITY.has(x.id)?1.5:0;return 1+weak+unseen+miss+breadth+personal;}
function pickWeighted(pool){const ws=pool.map(weightFor),sum=ws.reduce((a,b)=>a+b,0);let r=Math.random()*sum;for(let i=0;i<pool.length;i++){r-=ws[i];if(r<=0)return pool[i];}return pool[pool.length-1];}
function buildQueue(){const pool=[...BANK],out=[];while(out.length<SESSION_SIZE&&pool.length){const x=pickWeighted(pool);out.push(x);pool.splice(pool.indexOf(x),1);}return out;}
function chooseMode(x){const m=stats(x),unseen=m.attempts<2,r=Math.random(),lvl=state.level;if(unseen)return r<.55?"context":r<.80?"meaning":r<.95?"particle":"contrast";if(lvl<=3)return r<.45?"context":r<.70?"meaning":r<.90?"particle":"contrast";if(lvl<=7)return r<.30?"context":r<.45?"meaning":r<.75?"particle":r<.95?"contrast":"paraphrase";if(lvl<=11)return r<.20?"context":r<.30?"meaning":r<.65?"particle":r<.90?"contrast":"paraphrase";return r<.15?"context":r<.20?"meaning":r<.60?"particle":r<.85?"contrast":"paraphrase";}
function confusionBonus(target,candidate){return (state.confusions[target.id+"|"+candidate.id]||0)*3+(state.confusions[candidate.id+"|"+target.id]||0)*2;}
function rankedDistractors(target,mode){const parts=target.pv.split(" "),base=parts[0],particle=parts.slice(1).join(" ");return BANK.filter(x=>x.id!==target.id).map(x=>{const xp=x.pv.split(" "),xbase=xp[0],xparticle=xp.slice(1).join(" ");let score=Math.random();if(xbase===base)score+=mode==="contrast"||mode==="particle"?22:13;if(x.tag===target.tag)score+=9;if(xparticle===particle)score+=3;if(x.difficulty===target.difficulty)score+=2;score+=confusionBonus(target,x);return{x,score};}).sort((a,b)=>b.score-a.score).map(o=>o.x);}
function pickDistractors(target,mode,count=3){const ranked=rankedDistractors(target,mode),lvl=state.level,windowSize=lvl<=3?14:lvl<=7?9:lvl<=11?6:4,top=ranked.slice(0,Math.min(windowSize,ranked.length)),out=[];while(out.length<count&&top.length){const span=Math.min(lvl>=12?3:lvl>=8?4:6,top.length),i=Math.floor(Math.random()*span);out.push(top.splice(i,1)[0]);}return out;}
function particleOf(x){return x.pv.split(" ").slice(1).join(" ");}
function particleOptions(target){const base=target.pv.split(" ")[0],same=BANK.filter(x=>x.id!==target.id&&x.pv.split(" ")[0]===base).map(particleOf),fallback=["up","out","off","on","over","back","in","into","with","for","after","by","about","across"];const correct=particleOf(target),pool=[...new Set([...same,...fallback].filter(x=>x&&x!==correct))];return shuffle([correct,...shuffle(pool).slice(0,3)]);}
function contextFor(x,index){const m=stats(x);return x.contexts[(m.attempts+index)%x.contexts.length];}
function makeQuestion(target,index){let mode=chooseMode(target);if(mode==="paraphrase"&&!TRANSFORMS[target.id])mode="contrast";const ds=pickDistractors(target,mode),ctx=contextFor(target,index);if(mode==="meaning")return{target,mode,text:target.pv.toUpperCase()+" = ?",correctKey:target.id,options:shuffle([{key:target.id,text:target.en,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.en,confusionId:x.id}))])};
if(mode==="particle"){const base=target.pv.split(" ")[0],correct=particleOf(target),opts=particleOptions(target);return{target,mode,text:ctx.replace("___",base+" ___"),correctKey:correct,options:opts.map(x=>({key:x,text:x,confusionId:null}))};}
if(mode==="paraphrase")return{target,mode,text:TRANSFORMS[target.id],correctKey:target.id,options:shuffle([{key:target.id,text:target.pv,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.pv,confusionId:x.id}))])};
return{target,mode,text:ctx,correctKey:target.id,options:shuffle([{key:target.id,text:target.pv,confusionId:target.id},...ds.map(x=>({key:x.id,text:x.pv,confusionId:x.id}))])};}
async function startSession(){await ensureAudio();session={queue:buildQueue(),index:0,correct:0,times:[],errors:[],started:Date.now(),snapshot:JSON.stringify(state)};$("sessionLevel").textContent="L"+state.level;showScreen("gameScreen");renderSegments();nextQuestion();}
function renderSegments(){const box=$("segments");box.innerHTML="";for(let i=0;i<SESSION_SIZE;i++){const d=document.createElement("div");d.className="seg"+(session&&i<session.index?" on":"");box.appendChild(d);}}
function nextQuestion(){clearInterval(timerHandle);locked=false;lastTickShown=TIME_LIMIT+1;lastUrgentBeat=-1;$("correctReveal").classList.remove("show");if(!session||session.index>=SESSION_SIZE){finishSession();return;}current=makeQuestion(session.queue[session.index],session.index);$("qIndex").textContent=session.index+1;$("questionText").textContent=current.text;const box=$("answers");box.innerHTML="";current.options.forEach(o=>{const b=document.createElement("button");b.className="answer";b.textContent=o.text;b.dataset.key=o.key;b.addEventListener("click",()=>answer(o));box.appendChild(b);});deadline=Date.now()+TIME_LIMIT*1000;tick();timerHandle=setInterval(tick,50);}
function audioSupported(){return !!(window.AudioContext||window.webkitAudioContext);}
async function ensureAudio(){
  try{
    const AC=window.AudioContext||window.webkitAudioContext;
    if(!AC){soundOn=false;refreshSoundButton();return false;}
    if(!audioCtx)audioCtx=new AC();
    if(audioCtx.state==='suspended')await audioCtx.resume();
    const ok=audioCtx.state==='running';if(!ok){soundOn=false;refreshSoundButton();}return ok;
  }catch(e){console.warn("Audio unavailable",e);soundOn=false;refreshSoundButton();return false;}
}
function tone(freq,dur=.035,gain=.018,type='sine',delay=0){
  if(!soundOn||!audioCtx||audioCtx.state!=='running')return;
  const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();
  o.type=type;o.frequency.setValueAtTime(freq,t);
  g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.01);
}
function playTick(strong=false,step=0){const f=strong?(step%2?1540:1260):(step%2?1280:980);tone(f,strong?.034:.026,strong?.026:.016,'square');}
function playUrgentTimerPulse(left,beat=0){const final=left<=2,f=final?(beat%2?1660:1450):(beat%2?1360:1160);tone(f,final?.034:.028,final?.016:.012,final?'square':'triangle');if(left<=.55)tone(1960,.042,.010,'sine',.014);}
function playCorrect(){const notes=[440,587.33,783.99,1046.5];notes.forEach((f,i)=>{tone(f,i===3?.11:.052,i===3?.024:.020,i%2?'sine':'triangle',i*.047);if(i>0)tone(f*2,.032,.007,'sine',i*.047+.012);});}
function playWrong(){tone(311.13,.050,.020,'triangle');tone(220,.070,.017,'sine',.042);}
const LEVEL_SCORE_ROOTS=[146.83,155.56,164.81,174.61,196.00,220.00,246.94,261.63,293.66,329.63,349.23,392.00,440.00,493.88,523.25];
function semitoneHz(root,n){return root*Math.pow(2,n/12);}
function playLevelScore(correct,total=15){
  const rank=Math.max(1,Math.min(15,Math.round(15*(Number(correct)||0)/Math.max(1,Number(total)||15)))),root=LEVEL_SCORE_ROOTS[rank-1];
  let intervals=[0],step=.105,dur=.085,gain=.015,type='triangle';
  if(rank<=3){intervals=[0,-1,-5];step=.11;dur=.11;gain=.014;type='triangle';}
  else if(rank<=6){intervals=[0,3,0];step=.095;dur=.095;gain=.015;type='sine';}
  else if(rank<=9){intervals=[0,2,4];step=.085;dur=.085;gain=.017;type='triangle';}
  else if(rank<=12){intervals=[0,4,7,12];step=.075;dur=.09;gain=.019;type='triangle';}
  else if(rank<=14){intervals=[0,4,7,12,16];step=.068;dur=.095;gain=.021;type='sine';}
  else{intervals=[0,4,7,12,16,19,24];step=.062;dur=.105;gain=.024;type='triangle';}
  intervals.forEach((semi,i)=>{const delay=i*step,f=semitoneHz(root,semi);tone(f,i===intervals.length-1?dur*1.8:dur,gain,type,delay);if(rank>=10&&i>=2)tone(f*2,.045,gain*.24,'sine',delay+.012);});
  if(rank>=13){const finale=(intervals.length-1)*step+.07;tone(root/2,.22,gain*.8,'sine',finale);[0,4,7,12].forEach((semi,i)=>tone(semitoneHz(root,semi),rank===15?.28:.20,gain*(rank===15?.72:.55),i%2?'sine':'triangle',finale+i*.012));}
  if(rank===15){const crown=(intervals.length-1)*step+.30;[12,16,19,24].forEach((semi,i)=>tone(semitoneHz(root,semi),.18,.012,'sine',crown+i*.045));}
}
function haptic(ok){
  try{if(navigator.vibrate)navigator.vibrate(ok?18:[24,16,42]);}catch(e){}
}
function pulseFeedback(ok){
  const cls=ok?"feedback-correct":"feedback-wrong";
  document.body.classList.remove("feedback-correct","feedback-wrong");
  void document.body.offsetWidth;
  document.body.classList.add(cls);
  setTimeout(()=>document.body.classList.remove(cls),430);
}
function burstParticles(anchor){
  if(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;
  const layer=$("particles");if(!layer)return;
  const r=anchor&&anchor.getBoundingClientRect?anchor.getBoundingClientRect():null;
  const cx=r?r.left+r.width/2:innerWidth/2,cy=r?r.top+r.height/2:innerHeight*.55;
  const colors=[COLOR_BANDS_15[14],COLOR_BANDS_15[13],COLOR_BANDS_15[12],COLOR_BANDS_15[11],COLOR_BANDS_15[9]];
  for(let i=0;i<6;i++){
    const p=document.createElement("i"),a=(Math.PI*2*i/6)+(Math.random()-.5)*.28,d=26+Math.random()*42;
    p.className="particle";p.style.left=cx+"px";p.style.top=cy+"px";
    p.style.setProperty("--dx",Math.cos(a)*d+"px");p.style.setProperty("--dy",Math.sin(a)*d+"px");
    p.style.setProperty("--rot",Math.round((Math.random()-.5)*180)+"deg");p.style.setProperty("--size",(4+Math.random()*4)+"px");
    p.style.setProperty("--delay",Math.round(Math.random()*70)+"ms");p.style.setProperty("--particle-color",colors[i%colors.length]);
    layer.appendChild(p);setTimeout(()=>p.remove(),460);
  }
}
function refreshSoundButton(){const b=$("soundBtn");if(!b)return;if(!audioSupported()){soundOn=false;b.disabled=true;b.textContent='🔇';b.setAttribute('aria-label','Audio unavailable');b.title='Audio unavailable';return;}b.disabled=false;b.textContent=soundOn?'🔊':'🔇';b.setAttribute('aria-label',soundOn?'Sound on':'Sound off');b.title='';}
function tick(){const ms=Math.max(0,deadline-Date.now()),sec=ms/1000,pct=ms/(TIME_LIMIT*1000)*100,shown=Math.ceil(sec);$("timerText").textContent=sec.toFixed(1);$("timer").style.setProperty("--timer-cut",(100-pct)+"%");$("timer").classList.toggle("urgent",sec<=3);if(sec>3&&shown<lastTickShown&&shown>0&&shown<TIME_LIMIT){playTick(false,shown);lastTickShown=shown;}if(sec<=3&&sec>0){const beat=sec>2?Math.floor((3-sec)*2):100+Math.floor((2-sec)*4);if(beat!==lastUrgentBeat){lastUrgentBeat=beat;playUrgentTimerPulse(sec,beat);}}if(ms<=0){clearInterval(timerHandle);answer(null,true);}}
function showCorrectReveal(target){const pos=Math.max(1,current.options.findIndex(o=>o.key===current.correctKey)+1);const el=$("correctReveal");el.className="correct-reveal show pos-"+pos;el.innerHTML='<div class="correct-reveal-kicker"><i></i>CORRECT ANSWER</div><strong>'+target.pv+'</strong>';}
function answer(option,timeout=false){if(locked)return;locked=true;clearInterval(timerHandle);const elapsed=clamp((TIME_LIMIT*1000-Math.max(0,deadline-Date.now()))/1000,0,TIME_LIMIT),target=current.target,ok=!!option&&option.key===current.correctKey,m=stats(target),mm=m.modes[current.mode];m.attempts++;m.totalTime+=elapsed;m.avgTime=m.totalTime/m.attempts;m.lastSeen=Date.now();mm.attempts++;state.answers++;state.studySec+=elapsed;if(ok){m.correct++;m.streak++;m.bestStreak=Math.max(m.bestStreak,m.streak);mm.correct++;state.correct++;session.correct++;if(elapsed<=4)m.automatic++;}else{m.streak=0;m.misses++;let wrongId=option?.confusionId||null;if(!wrongId&&option&&current.mode==="particle"){const base=target.pv.split(" ")[0],cand=BANK.find(x=>x.id!==target.id&&x.pv.split(" ")[0]===base&&particleOf(x)===option.key);wrongId=cand?.id||null;}if(wrongId){const key=target.id+"|"+wrongId;state.confusions[key]=(state.confusions[key]||0)+1;}session.errors.push({target:target.id,choice:wrongId,shown:option?.text||null,timeout,mode:current.mode,question:current.text});}
state.answerHistory.push({id:target.id,mode:current.mode,ok,time:elapsed,at:Date.now()});state.answerHistory=state.answerHistory.slice(-1200);session.times.push(elapsed);const buttons=[...$("answers").children];buttons.forEach(b=>{b.disabled=true;if(b.dataset.key===current.correctKey)b.classList.add("good");else if(option&&b.dataset.key===option.key)b.classList.add("bad");else b.classList.add("dim");});if(!ok)showCorrectReveal(target);showFeedback(ok,timeout,target);try{if(ok)playCorrect();else playWrong();haptic(ok);pulseFeedback(ok);if(ok&&option){const chosen=buttons.find(b=>b.dataset.key===option.key);if(chosen)burstParticles(chosen);}}catch(e){console.warn("Feedback audio unavailable",e);}save();setTimeout(()=>{session.index++;renderSegments();nextQuestion();},ok?555:1050);}
function showFeedback(ok,timeout,target){const f=$("feedback");f.className="feedback "+(ok?"ok":"no");f.innerHTML='<div class="feedback-label">'+(ok?"CORRECT":timeout?"TIME":"NOT QUITE")+'</div><div class="appearance">'+target.pv+'</div><small>'+target.en+'</small>';requestAnimationFrame(()=>f.classList.add("show"));setTimeout(()=>f.classList.remove("show"),560);}
function finishSession(){clearInterval(timerHandle);const acc=session.correct/SESSION_SIZE,old=state.level;if(acc>=.80)state.level=Math.min(15,state.level+1);else if(acc<.47)state.level=Math.max(1,state.level-1);state.sessions++;const learning=rating();state.history.push({at:Date.now(),score:session.correct,total:SESSION_SIZE,levelBefore:old,levelAfter:state.level,avgTime:session.times.reduce((a,b)=>a+b,0)/session.times.length,learning});state.history=state.history.slice(-400);save();playLevelScore(session.correct,SESSION_SIZE);renderEnd(old);showScreen("endScreen");}
function lessonItem(){if(session.errors.length)return BY_ID[session.errors[0].target];return [...session.queue].sort((a,b)=>mastery(a)-mastery(b))[0];}
function renderLesson(){const x=lessonItem();if(!x){$("levelLesson").classList.add("hidden");return;}const example=x.contexts[0].replace("___",x.pv);$("levelLesson").classList.remove("hidden");$("levelLesson").innerHTML='<div class="lesson-kicker">LEVEL FLASHCARD · ENGLISH ONLY</div><h2>'+x.pv+'</h2><div class="lesson-source"><b>Meaning:</b> '+x.en+'</div><div class="lesson-formula">'+x.pv.toUpperCase()+'</div><div class="lesson-example"><strong>Example</strong>'+example+'</div><div class="lesson-cue">Mastery '+mastery(x)+'% · '+modeBreadth(x)+'/5 exercise modes seen.</div>';}
function renderEnd(old){applyTheme();const acc=Math.round(session.correct/SESSION_SIZE*100),avg=session.times.reduce((a,b)=>a+b,0)/session.times.length;$("endScore").textContent=session.correct+"/15";$("endSub").textContent=state.level>old?"Level up · harder contrasts unlocked.":state.level<old?"Level adjusted · weak contrasts recycled.":"Level held · difficulty rebalanced.";$("eAvg").textContent=avg.toFixed(1)+"s";$("eAuto").textContent=automaticPct()+"%";$("eRating").textContent=rating();$("eCoverage").textContent=coverage()+"%";$("eMastery").textContent=globalMastery()+"%";$("eMastered").textContent=BANK.filter(mastered).length+"/"+BANK.length;$("weakSkills").innerHTML=skillRows(focusItems());const has=session.errors.length>0;for(const id of ["errorsBtn","topErrorsBtn"])$(id).classList.toggle("hidden",!has);const medal=window.AdrianAchievements?.badgeHtml?.(session.correct,SESSION_SIZE)||"";const ah=$("achievementHost");if(ah)ah.innerHTML=medal;if(medal)window.AdrianAchievements?.play?.(tone,session.correct,SESSION_SIZE);renderLesson();}
function renderErrors(){const box=$("errorsFull");$("errorsCount").textContent=session?.errors?.length?session.errors.length+" mistakes in the latest level.":"No mistakes in the latest level.";if(!session?.errors?.length){box.innerHTML='<div class="statusbox">Perfect level.</div>';return;}box.innerHTML=session.errors.map(e=>{const t=BY_ID[e.target],c=e.choice?BY_ID[e.choice]:null;return '<div class="mistake-card"><b>'+t.pv+' · '+e.mode.toUpperCase()+'</b><p>'+e.question+'</p><div class="mistake-choice"><div>'+(e.timeout?"TIME":e.shown?("Your answer: "+e.shown):"Wrong answer")+'</div><div class="correct">Correct: '+t.pv+' · '+t.en+'</div></div>'+(c?'<p>Confused with <strong>'+c.pv+'</strong>: '+c.en+'</p>':'')+'</div>';}).join("");}
function openErrors(){renderErrors();showScreen("errorsScreen");}
function renderFlash(){const x=flashQueue[flashIndex%flashQueue.length];if(!x)return;flashRevealed=false;$("flashAgainBtn").textContent="SHOW ANSWER";const example=x.contexts[0];$("flashCardHost").innerHTML='<div class="lesson-kicker">CARD '+(flashIndex+1)+' / '+flashQueue.length+' · MASTERY '+mastery(x)+'%</div><h2>Which phrasal verb?</h2><div class="lesson-source"><b>Meaning:</b> '+x.en+'</div><div class="lesson-example"><strong>Context</strong>'+example+'</div><div id="flashReveal" class="lesson-formula hidden">'+x.pv.toUpperCase()+'</div><div class="lesson-cue">'+modeBreadth(x)+'/5 exercise modes seen · '+stats(x).attempts+' adaptive attempts.</div>';}
function openFlash(){flashQueue=[...BANK].sort((a,b)=>mastery(a)-mastery(b)||stats(a).attempts-stats(b).attempts);flashIndex=0;renderFlash();showScreen("flashScreen");}
function toggleFlash(){flashRevealed=!flashRevealed;$("flashReveal").classList.toggle("hidden",!flashRevealed);$("flashAgainBtn").textContent=flashRevealed?"HIDE ANSWER":"SHOW ANSWER";}
function nextFlash(){flashIndex=(flashIndex+1)%flashQueue.length;renderFlash();}
function goHome(){clearInterval(timerHandle);session=null;current=null;renderHome();showScreen("startScreen");}
function abortSession(){clearInterval(timerHandle);if(session?.snapshot){state=JSON.parse(session.snapshot);for(const x of BANK)state.items[x.id]=normalizeItem(state.items[x.id]);save();}goHome();}
function exportProgress(){const blob=new Blob([JSON.stringify({app:"adaptive-phrasal-verbs",version:APP_VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="adaptive-phrasal-verbs-progress.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importProgressFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result),incoming=data.state||data;if(!incoming||typeof incoming!=="object")throw new Error("Invalid backup");localStorage.setItem(STORAGE_KEY,JSON.stringify(incoming));state=loadState();renderHome();if(window.AdaptiveLanguageDashboard)window.AdaptiveLanguageDashboard.refresh();}catch(e){alert("Could not import this progress backup.");}};r.readAsText(file);}
function resetProgress(){if(!confirm("Reset Adaptive Phrasal Verbs progress?"))return;localStorage.removeItem(STORAGE_KEY);state=loadState();renderHome();if(window.AdaptiveLanguageDashboard)window.AdaptiveLanguageDashboard.refresh();}
async function setSound(){soundOn=!soundOn;if(soundOn){await ensureAudio();tone(760,.06,.025,"sine");}refreshSoundButton();}
$("startBtn").addEventListener("click",startSession);$("continueBtn").addEventListener("click",startSession);$("topContinueBtn").addEventListener("click",startSession);$("homeBtn").addEventListener("click",goHome);$("topHomeBtn").addEventListener("click",goHome);$("abortSessionBtn").addEventListener("click",abortSession);$("soundBtn").addEventListener("click",setSound);
$("statsBtn").addEventListener("click",()=>{if(window.AdaptiveLanguageDashboard)return window.AdaptiveLanguageDashboard.open();renderStats();showScreen("statsScreen");});$("statsBackBtn").addEventListener("click",goHome);$("statsTopDashboardBtn").addEventListener("click",goHome);
$("flashBtn").addEventListener("click",openFlash);$("flashAgainBtn").addEventListener("click",toggleFlash);$("flashNextBtn").addEventListener("click",nextFlash);$("flashBackBtn").addEventListener("click",goHome);$("flashTopDashboardBtn").addEventListener("click",goHome);
$("exportBtn").addEventListener("click",exportProgress);$("importBtn").addEventListener("click",()=>$("importFile").click());$("importFile").addEventListener("change",e=>importProgressFile(e.target.files?.[0]));$("resetBtn").addEventListener("click",resetProgress);
$("errorsBtn").addEventListener("click",openErrors);$("topErrorsBtn").addEventListener("click",openErrors);$("errorsBackBtn").addEventListener("click",()=>showScreen("endScreen"));$("errorsTopDashboardBtn").addEventListener("click",goHome);
document.addEventListener("visibilitychange",()=>{if(document.hidden&&timerHandle)clearInterval(timerHandle);else if(!document.hidden&&session&&!locked&&current){deadline=Date.now()+Math.min(TIME_LIMIT,parseFloat($("timerText").textContent)||TIME_LIMIT)*1000;lastTickShown=Math.ceil(parseFloat($("timerText").textContent)||TIME_LIMIT)+1;lastUrgentBeat=-1;timerHandle=setInterval(tick,50);}});
refreshSoundButton();renderHome();showScreen("startScreen");
