window.PHRASAL_BANK = Object.freeze([
{id:"bring_up",pv:"bring up",en:"mention a topic",es:"mencionar un tema",tag:"discussion",difficulty:2,contexts:["Don't ___ that topic now.","She may ___ the issue later."]},
{id:"call_off",pv:"call off",en:"cancel a plan",es:"cancelar",tag:"plans",difficulty:2,contexts:["They may ___ the match.","We had to ___ dinner."]},
{id:"carry_on",pv:"carry on",en:"continue doing",es:"continuar",tag:"continue",difficulty:1,contexts:["Please ___ with your work.","She can ___ talking despite the noise."]},
{id:"carry_out",pv:"carry out",en:"perform a task",es:"llevar a cabo",tag:"action",difficulty:2,contexts:["They will ___ the test.","We must ___ the plan."]},
{id:"catch_up_with",pv:"catch up with",en:"reach the same level",es:"alcanzar",tag:"progress",difficulty:2,contexts:["I need to ___ the class.","Run to ___ them."]},
{id:"check_out",pv:"check out",en:"look at or examine",es:"echar un vistazo",tag:"discovery",difficulty:2,contexts:["___ this new app.","Let's ___ that café."]},
{id:"come_across",pv:"come across",en:"find by chance",es:"encontrarse por casualidad",tag:"discovery",difficulty:2,contexts:["I happened to ___ an old photo.","You may ___ strange words."]},
{id:"come_up_with",pv:"come up with",en:"think of an idea",es:"idear",tag:"ideas",difficulty:2,contexts:["Can you ___ a name?","We need to ___ a plan."]},
{id:"cut_off",pv:"cut off",en:"disconnect or interrupt",es:"cortar o interrumpir",tag:"connection",difficulty:2,contexts:["The call may ___ suddenly.","Don't ___ people speaking."]},
{id:"end_up",pv:"end up",en:"finally become or arrive",es:"acabar",tag:"result",difficulty:2,contexts:["We could ___ lost.","He could ___ paying twice."]},
{id:"find_out",pv:"find out",en:"discover information",es:"averiguar",tag:"discovery",difficulty:1,contexts:["I need to ___ why.","Let's ___ the price."]},
{id:"get_back",pv:"get back",en:"return",es:"volver",tag:"movement",difficulty:1,contexts:["When did you ___?","I'll ___ before eight."]},
{id:"get_by",pv:"get by",en:"manage with little",es:"apañárselas",tag:"progress",difficulty:3,contexts:["He can ___ on little money.","My Italian helps me ___."]},
{id:"get_over",pv:"get over",en:"recover from",es:"recuperarse de",tag:"recovery",difficulty:2,contexts:["She will ___ the flu.","He can't ___ the shock."]},
{id:"get_rid_of",pv:"get rid of",en:"remove something",es:"deshacerse de",tag:"recovery",difficulty:2,contexts:["Let's ___ these boxes.","I need to ___ clutter."]},
{id:"give_in",pv:"give in",en:"stop resisting",es:"ceder",tag:"yield",difficulty:2,contexts:["Don't ___ so easily.","He finally decided to ___."]},
{id:"give_up",pv:"give up",en:"stop trying",es:"rendirse o dejar",tag:"yield",difficulty:1,contexts:["Don't ___ now.","She decided to ___ smoking."]},
{id:"go_on",pv:"go on",en:"continue or happen",es:"continuar o suceder",tag:"continue",difficulty:1,contexts:["Please ___ with the story.","What is going to ___?"]},
{id:"grow_up",pv:"grow up",en:"become an adult",es:"crecer",tag:"life",difficulty:1,contexts:["Where did you ___?","Kids change as they ___."]},
{id:"hand_in",pv:"hand in",en:"submit something",es:"entregar",tag:"study",difficulty:1,contexts:["___ your work today.","Please ___ the form."]},{id:"hang_out",pv:"hang out",en:"spend time socially",es:"pasar el rato",tag:"social",difficulty:1,contexts:["We ___ after class.","Do you want to ___?"]},
{id:"help_out",pv:"help out",en:"give practical help",es:"echar una mano",tag:"social",difficulty:1,contexts:["Can you ___ today?","She offered to ___."]},
{id:"keep_up_with",pv:"keep up with",en:"match the pace",es:"seguir el ritmo",tag:"continue",difficulty:3,contexts:["I can't ___ the class.","Can you ___ her pace?"]},
{id:"lead_up_to",pv:"lead up to",en:"happen before and cause",es:"conducir a",tag:"result",difficulty:3,contexts:["What could ___ the crisis?","These events ___ the decision."]},
{id:"look_after",pv:"look after",en:"take care of",es:"cuidar",tag:"social",difficulty:1,contexts:["Can you ___ my bag?","She must ___ her brother."]},
{id:"look_forward_to",pv:"look forward to",en:"feel excited about",es:"tener ganas de",tag:"social",difficulty:2,contexts:["I ___ seeing you.","We ___ the weekend."]},
{id:"look_into",pv:"look into",en:"investigate",es:"investigar",tag:"discovery",difficulty:2,contexts:["They will ___ the complaint.","Please ___ this problem."]},
{id:"look_up",pv:"look up",en:"search for information",es:"buscar información",tag:"discovery",difficulty:1,contexts:["___ the word online.","I'll ___ the train time."]},
{id:"meet_up",pv:"meet up",en:"meet socially",es:"quedar",tag:"social",difficulty:1,contexts:["Let's ___ tomorrow.","We ___ after work."]},
{id:"move_on",pv:"move on",en:"continue to something new",es:"seguir adelante",tag:"progress",difficulty:2,contexts:["Let's ___ now.","It's time to ___."]},
{id:"pick_up",pv:"pick up",en:"collect or learn informally",es:"recoger o aprender",tag:"learning",difficulty:2,contexts:["I'll ___ the tickets.","You can ___ slang quickly."]},
{id:"put_off",pv:"put off",en:"postpone",es:"aplazar",tag:"plans",difficulty:2,contexts:["Don't ___ the task.","They may ___ the trip."]},
{id:"put_on",pv:"put on",en:"wear or organise",es:"ponerse u organizar",tag:"put",difficulty:2,contexts:["___ your coat.","They will ___ a show."]},
{id:"put_up_with",pv:"put up with",en:"tolerate",es:"soportar",tag:"put",difficulty:3,contexts:["I can't ___ this noise.","How do you ___ it?"]},
{id:"run_out_of",pv:"run out of",en:"have none left",es:"quedarse sin",tag:"supply",difficulty:2,contexts:["We may ___ milk.","Don't ___ water."]},
{id:"set_about",pv:"set about",en:"begin a task",es:"ponerse a hacer",tag:"action",difficulty:3,contexts:["She can ___ fixing it.","We ___ cleaning the room."]},
{id:"set_off",pv:"set off",en:"start a journey",es:"ponerse en camino",tag:"movement",difficulty:2,contexts:["We should ___ early.","They ___ at dawn."]},
{id:"set_up",pv:"set up",en:"establish or arrange",es:"montar o establecer",tag:"plans",difficulty:2,contexts:["She will ___ a business.","Let's ___ a meeting."]},
{id:"sign_up_for",pv:"sign up for",en:"register for",es:"apuntarse a",tag:"study",difficulty:2,contexts:["I'll ___ the course.","Did you ___ the workshop?"]},
{id:"split_up",pv:"split up",en:"separate or end a relationship",es:"separarse o romper",tag:"social",difficulty:2,contexts:["They decided to ___.","Let's ___ into pairs."]},{id:"stand_up_for",pv:"stand up for",en:"defend",es:"defender",tag:"discussion",difficulty:3,contexts:["You should ___ yourself.","She will ___ her team."]},
{id:"stick_to",pv:"stick to",en:"keep following",es:"mantenerse fiel a",tag:"continue",difficulty:3,contexts:["___ the plan.","Please ___ the question."]},
{id:"take_off",pv:"take off",en:"leave the ground or remove",es:"despegar o quitarse",tag:"take",difficulty:1,contexts:["The plane will ___ soon.","You can ___ your coat."]},
{id:"take_on",pv:"take on",en:"accept work or responsibility",es:"asumir",tag:"take",difficulty:3,contexts:["Don't ___ more work.","They will ___ new staff."]},
{id:"take_over",pv:"take over",en:"gain control",es:"hacerse cargo",tag:"take",difficulty:3,contexts:["She will ___ next month.","Can you ___ for me?"]},
{id:"take_part_in",pv:"take part in",en:"participate in",es:"participar en",tag:"study",difficulty:1,contexts:["Will you ___ the event?","Many students ___ it."]},
{id:"take_up",pv:"take up",en:"start an activity",es:"empezar una actividad",tag:"take",difficulty:2,contexts:["She may ___ yoga.","I want to ___ painting."]},
{id:"turn_out",pv:"turn out",en:"prove to be",es:"resultar",tag:"result",difficulty:3,contexts:["It may ___ fine.","The test may ___ easy."]},
{id:"turn_up",pv:"turn up",en:"arrive or appear",es:"aparecer",tag:"movement",difficulty:2,contexts:["He didn't ___ yesterday.","The keys may ___ later."]},
{id:"work_out",pv:"work out",en:"solve or understand",es:"resolver",tag:"result",difficulty:2,contexts:["Can you ___ the answer?","We'll ___ the problem."]},
{id:"back_up",pv:"back up",en:"support or make a copy",es:"apoyar o hacer copia",tag:"support",difficulty:2,contexts:["Can you ___ my claim?","Remember to ___ the files."]},
{id:"break_down",pv:"break down",en:"stop working or collapse",es:"averiarse o derrumbarse",tag:"break",difficulty:2,contexts:["The car may ___.","She began to ___ crying."]},
{id:"break_in",pv:"break in",en:"enter by force",es:"entrar por la fuerza",tag:"break",difficulty:2,contexts:["Someone tried to ___.","Thieves may ___ at night."]},
{id:"break_into",pv:"break into",en:"enter a place by force",es:"entrar por la fuerza en",tag:"break",difficulty:2,contexts:["They tried to ___ the shop.","Someone tried to ___ the house."]},
{id:"break_out",pv:"break out",en:"start suddenly",es:"estallar",tag:"break",difficulty:2,contexts:["A fire could ___.","Fighting may ___ again."]},
{id:"break_up",pv:"break up",en:"separate or end",es:"separarse",tag:"break",difficulty:2,contexts:["They may ___ soon.","The group decided to ___."]},
{id:"bring_back",pv:"bring back",en:"return or revive",es:"traer de vuelta",tag:"bring",difficulty:2,contexts:["Please ___ my book.","That song can ___ memories."]},
{id:"bring_about",pv:"bring about",en:"cause something",es:"provocar",tag:"bring",difficulty:3,contexts:["What could ___ the change?","This could ___ reform."]},
{id:"bring_in",pv:"bring in",en:"introduce or earn",es:"introducir o generar",tag:"bring",difficulty:2,contexts:["They may ___ a new rule.","The job may ___ extra money."]},
{id:"bring_out",pv:"bring out",en:"release or reveal",es:"sacar o resaltar",tag:"bring",difficulty:2,contexts:["They will ___ a new model.","Blue can ___ her eyes."]},{id:"call_back",pv:"call back",en:"return a phone call",es:"devolver una llamada",tag:"call",difficulty:1,contexts:["I'll ___ later.","Can you ___ at six?"]},
{id:"call_for",pv:"call for",en:"require or demand",es:"requerir o pedir",tag:"call",difficulty:3,contexts:["This may ___ patience.","They ___ stricter rules."]},
{id:"calm_down",pv:"calm down",en:"become calmer",es:"calmarse",tag:"emotion",difficulty:1,contexts:["Please ___ first.","He soon began to ___."]},
{id:"check_in",pv:"check in",en:"register on arrival",es:"registrarse",tag:"travel",difficulty:1,contexts:["We need to ___ now.","You can ___ online."]},
{id:"come_back",pv:"come back",en:"return",es:"volver",tag:"movement",difficulty:1,contexts:["Please ___ soon.","When did she ___?"]},
{id:"come_down_with",pv:"come down with",en:"become ill with",es:"ponerse enfermo de",tag:"recovery",difficulty:3,contexts:["I may ___ a cold.","He may ___ the flu."]},
{id:"come_out",pv:"come out",en:"be released or appear",es:"salir o publicarse",tag:"result",difficulty:2,contexts:["The results ___ tomorrow.","Her new book may ___ soon."]},
{id:"count_on",pv:"count on",en:"rely on",es:"contar con",tag:"support",difficulty:2,contexts:["You can ___ me.","Don't ___ good weather."]},
{id:"cut_down_on",pv:"cut down on",en:"reduce consumption",es:"reducir",tag:"change",difficulty:2,contexts:["I should ___ sugar.","Try to ___ coffee."]},
{id:"do_without",pv:"do without",en:"manage without",es:"prescindir de",tag:"supply",difficulty:3,contexts:["We can ___ a car.","I can't ___ coffee."]},
{id:"drop_off",pv:"drop off",en:"leave someone or fall asleep",es:"dejar o dormirse",tag:"movement",difficulty:2,contexts:["I'll ___ you there.","I ___ on the sofa."]},
{id:"figure_out",pv:"figure out",en:"understand or solve",es:"averiguar o resolver",tag:"result",difficulty:2,contexts:["Can you ___ the code?","I can't ___ why."]},
{id:"fill_in",pv:"fill in",en:"complete missing information",es:"rellenar",tag:"study",difficulty:1,contexts:["___ your name here.","Please ___ the blanks."]},
{id:"fill_out",pv:"fill out",en:"complete a form",es:"rellenar un formulario",tag:"study",difficulty:1,contexts:["___ this form.","Please ___ the application."]},
{id:"get_along_with",pv:"get along with",en:"have a good relationship",es:"llevarse bien con",tag:"social",difficulty:2,contexts:["I ___ my boss.","Do you ___ them?"]},
{id:"get_away",pv:"get away",en:"escape or go on holiday",es:"escapar o irse",tag:"movement",difficulty:2,contexts:["The thief may ___.","We need to ___ soon."]},
{id:"get_away_with",pv:"get away with",en:"avoid punishment",es:"salirse con la suya",tag:"yield",difficulty:3,contexts:["He won't ___ cheating.","You can't ___ that."]},
{id:"get_down_to",pv:"get down to",en:"start doing seriously",es:"ponerse en serio",tag:"action",difficulty:3,contexts:["Let's ___ work.","I need to ___ studying."]},
{id:"get_off",pv:"get off",en:"leave transport",es:"bajarse",tag:"movement",difficulty:1,contexts:["We ___ at the next stop.","Where do I ___?"]},
{id:"get_on",pv:"get on",en:"enter transport or progress",es:"subirse o progresar",tag:"movement",difficulty:1,contexts:["___ the bus here.","We usually ___ here."]},{id:"get_on_with",pv:"get on with",en:"continue doing",es:"seguir con",tag:"continue",difficulty:2,contexts:["___ your work.","Let's ___ the job."]},
{id:"get_out",pv:"get out",en:"leave a place",es:"salir",tag:"movement",difficulty:1,contexts:["We need to ___ now.","How did they ___?"]},
{id:"get_through",pv:"get through",en:"finish or survive",es:"terminar o superar",tag:"progress",difficulty:3,contexts:["I must ___ this work.","She'll ___ the exam week."]},
{id:"go_ahead",pv:"go ahead",en:"proceed",es:"seguir adelante",tag:"action",difficulty:2,contexts:["You can ___ now.","They decided to ___."]},
{id:"go_off",pv:"go off",en:"explode, ring or stop liking",es:"sonar o explotar",tag:"change",difficulty:2,contexts:["The alarm may ___.","The bomb could ___."]},
{id:"go_over",pv:"go over",en:"review",es:"repasar",tag:"study",difficulty:2,contexts:["Let's ___ the notes.","I need to ___ this."]},
{id:"hold_on",pv:"hold on",en:"wait",es:"esperar",tag:"call",difficulty:1,contexts:["___ a second.","Please ___ while I check."]},
{id:"keep_on",pv:"keep on",en:"continue doing",es:"seguir haciendo",tag:"continue",difficulty:2,contexts:["He may ___ complaining.","Just ___ practising."]},
{id:"let_down",pv:"let down",en:"disappoint",es:"decepcionar",tag:"emotion",difficulty:2,contexts:["Don't ___ your team.","I won't ___ you."]},
{id:"look_around",pv:"look around",en:"explore a place",es:"mirar alrededor",tag:"discovery",difficulty:1,contexts:["Let's ___ the museum.","We had time to ___."]},
{id:"look_for",pv:"look for",en:"search for",es:"buscar",tag:"discovery",difficulty:1,contexts:["I need to ___ my keys.","Can you ___ this file?"]},
{id:"look_out",pv:"look out",en:"be careful",es:"tener cuidado",tag:"warning",difficulty:1,contexts:["___! A car!","You should ___ here."]},
{id:"look_over",pv:"look over",en:"check quickly",es:"revisar",tag:"discovery",difficulty:2,contexts:["Can you ___ my CV?","I'll ___ the report."]},
{id:"make_up",pv:"make up",en:"invent or reconcile",es:"inventar o reconciliarse",tag:"ideas",difficulty:2,contexts:["Don't ___ excuses.","They finally ___ after arguing."]},
{id:"pay_back",pv:"pay back",en:"return money",es:"devolver dinero",tag:"money",difficulty:1,contexts:["I'll ___ you tomorrow.","He still must ___ the loan."]},
{id:"point_out",pv:"point out",en:"draw attention to",es:"señalar",tag:"discussion",difficulty:2,contexts:["She may ___ the error.","I'd like to ___ one thing."]},
{id:"put_away",pv:"put away",en:"store in its place",es:"guardar",tag:"put",difficulty:1,contexts:["Please ___ your phone.","___ the dishes now."]},
{id:"put_out",pv:"put out",en:"extinguish",es:"apagar",tag:"put",difficulty:2,contexts:["They ___ the fire.","Please ___ the candle."]},
{id:"run_into",pv:"run into",en:"meet by chance",es:"encontrarse por casualidad",tag:"discovery",difficulty:2,contexts:["I often ___ Marta here.","You may ___ old friends."]},
{id:"sort_out",pv:"sort out",en:"solve or organise",es:"resolver u organizar",tag:"result",difficulty:2,contexts:["We need to ___ this mess.","I'll ___ the problem."]},{id:"show_up",pv:"show up",en:"arrive or appear",es:"aparecer",tag:"movement",difficulty:1,contexts:["He didn't ___ today.","She may ___ later."]},
{id:"speak_up",pv:"speak up",en:"speak louder",es:"hablar más alto",tag:"discussion",difficulty:1,contexts:["Please ___ a little.","You'll need to ___."]},
{id:"take_back",pv:"take back",en:"return or retract",es:"devolver o retirar",tag:"take",difficulty:2,contexts:["I need to ___ this shirt.","I ___ what I said."]},
{id:"take_down",pv:"take down",en:"remove or write",es:"bajar o anotar",tag:"take",difficulty:2,contexts:["Please ___ the poster.","Can you ___ my number?"]},
{id:"throw_away",pv:"throw away",en:"discard",es:"tirar",tag:"change",difficulty:1,contexts:["Don't ___ that box.","I should ___ these papers."]},
{id:"try_on",pv:"try on",en:"test clothing",es:"probarse",tag:"shopping",difficulty:1,contexts:["Can I ___ this jacket?","She wants to ___ the shoes."]},
{id:"turn_down",pv:"turn down",en:"reject or reduce",es:"rechazar o bajar",tag:"turn",difficulty:2,contexts:["She may ___ the offer.","Please ___ the music."]},
{id:"turn_off",pv:"turn off",en:"switch off",es:"apagar",tag:"turn",difficulty:1,contexts:["___ the light.","Please ___ your phone."]},
{id:"turn_on",pv:"turn on",en:"switch on",es:"encender",tag:"turn",difficulty:1,contexts:["___ the heater.","Can you ___ the TV?"]},
{id:"wake_up",pv:"wake up",en:"stop sleeping",es:"despertarse",tag:"life",difficulty:1,contexts:["I ___ at seven.","Please ___ early."]},
{id:"wear_out",pv:"wear out",en:"become unusable",es:"desgastarse",tag:"change",difficulty:2,contexts:["These shoes may ___ soon.","I ___ trainers quickly."]},
{id:"work_on",pv:"work on",en:"spend time improving",es:"trabajar en",tag:"action",difficulty:1,contexts:["I need to ___ my English.","She will ___ the report."]},
{id:"put_back",pv:"put back",en:"return to its place",es:"volver a poner",tag:"put",difficulty:1,contexts:["Please ___ the book.","___ the chair when done."]},
{id:"put_down",pv:"put down",en:"place down or criticise",es:"dejar o menospreciar",tag:"put",difficulty:2,contexts:["___ the bag here.","Don't ___ other people."]},
{id:"pull_over",pv:"pull over",en:"stop a vehicle",es:"orillarse",tag:"travel",difficulty:2,contexts:["Please ___ here.","The police made him ___."]},
{id:"pass_away",pv:"pass away",en:"die",es:"fallecer",tag:"life",difficulty:2,contexts:["People can ___ peacefully.","Some people ___ in their sleep."]},
{id:"log_in",pv:"log in",en:"enter an account",es:"iniciar sesión",tag:"technology",difficulty:1,contexts:["Please ___ first.","I can't ___ today."]},
{id:"log_out",pv:"log out",en:"leave an account",es:"cerrar sesión",tag:"technology",difficulty:1,contexts:["Remember to ___ after use.","Please ___ now."]},
{id:"set_aside",pv:"set aside",en:"reserve for later",es:"reservar",tag:"plans",difficulty:2,contexts:["___ some money each month.","We should ___ an hour."]},
{id:"look_back_on",pv:"look back on",en:"remember the past",es:"recordar el pasado",tag:"life",difficulty:3,contexts:["I ___ those years fondly.","She likes to ___ school."]}
]);